### ISSUE TITLE
TypeError: no default __reduce__ due to non-trivial __cinit__, when using multiprocessing

### ISSUE THREAD

**Issue by llan-ml** [openai/mujoco-py#215]
I notice that `MjSimPool` was removed recently. I wonder how to use native python multiprocessing apis to accelerate multiple simulations. I get the following error:
<pre>
In [41]: with futures.ProcessPoolExecutor() as executor:
    ...:     st = time.time()
    ...:     x = list(executor.map(step, [x.sim for x in envs]))
    ...:     print(time.time() - st)
    ...:
Traceback (most recent call last):
  File "/home/lanlin/.pyenv/versions/anaconda2-4.4.0/envs/mujoco-py/lib/python3.5/multiprocessing/queues.py", line 241, in _feed
    obj = ForkingPickler.dumps(obj)
  File "/home/lanlin/.pyenv/versions/anaconda2-4.4.0/envs/mujoco-py/lib/python3.5/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
  File "mujoco_py/mjbatchrenderer.pyx", line 2, in mujoco_py.cymj
TypeError: no default __reduce__ due to non-trivial __cinit__
</pre>

**Comment by mitsu3291** [comment]
Hi @llan-ml, I got the same error. Did you solve this?
