### ISSUE TITLE
Error while building 'mujoco_py.cymj' extension: cannot find libraries

### ISSUE THREAD

**Issue by matthew9671** [openai/mujoco-py#225]
I am working with a ubuntu 16.04 AWS machine in a virtual environment. I installed mujoco-py from source and when I try to import it within python3.6 it fails because gcc cannot find the libraries:

`>>> import mujoco_py
running build_ext
building 'mujoco_py.cymj' extension
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/cymj.o up to date, skipping.
/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/gl/osmesashim.o up to date, skipping.
gcc -pthread -shared -B /home/ubuntu/anaconda3/envs/tensorflow_p36/compiler_compat -L/home/ubuntu/anaconda3/envs/tensorflow_p36/lib -Wl,-rpath=/home/ubuntu/anaconda3/envs/tensorflow_p36/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/cymj.o /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/gl/osmesashim.o -L/home/ubuntu/.mujoco/mjpro150/bin -Wl,--enable-new-dtags,-R/home/ubuntu/.mujoco/mjpro150/bin -lmujoco150 -lglewosmesa -lOSMesa -lGL -o /home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
/home/ubuntu/anaconda3/envs/tensorflow_p36/compiler_compat/ld: cannot find -lOSMesa
/home/ubuntu/anaconda3/envs/tensorflow_p36/compiler_compat/ld: cannot find -lGL
/home/ubuntu/anaconda3/envs/tensorflow_p36/compiler_compat/ld: cannot find -lpthread
/home/ubuntu/anaconda3/envs/tensorflow_p36/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/__init__.py", line 1, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/builder.py", line 502, in <module>
    cymj = load_cython_ext(mjpro_path)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/builder.py", line 81, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/builder.py", line 238, in build
    built_so_file_path = self._build_impl()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/builder.py", line 261, in _build_impl
    dist.run_commands()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/mujoco_py-1.50.1.42-py3.6.egg/mujoco_py/builder.py", line 157, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1`

**Comment by matthew9671** [comment]
I realized it's because mujoco doesn't support python3.6 yet.
