### ISSUE TITLE
CartPole example crashes

### ISSUE THREAD

**Issue by chrisspen** [openai/mujoco-py#231]
I setup my environment with:

    apt-get install -y python-numpy python-dev cmake zlib1g-dev libjpeg-dev xvfb libav-tools xorg-dev python-opengl libboost-all-dev libsdl2-dev swig
    virtualenv -p python3 .env
    . .env/bin/activate
    pip install gym pyglet

and then when I went to run the CartPole example:

    #!/usr/bin/env python
    import gym
    env = gym.make('CartPole-v0')
    env.reset()
    env.render()

it crashes with the Traceback:

    WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
    Exception ignored in: <bound method Viewer.__del__ of <gym.envs.classic_control.rendering.Viewer object at 0x7f14cd33f9b0>>
    Traceback (most recent call last):
      File "/tmp/gym/.env/lib/python3.5/site-packages/gym/envs/classic_control/rendering.py", line 143, in __del__
      File "/tmp/gym/.env/lib/python3.5/site-packages/gym/envs/classic_control/rendering.py", line 62, in close
      File "/tmp/gym/.env/lib/python3.5/site-packages/pyglet/window/xlib/__init__.py", line 480, in close
      File "/tmp/gym/.env/lib/python3.5/site-packages/pyglet/gl/xlib.py", line 345, in destroy
      File "/tmp/gym/.env/lib/python3.5/site-packages/pyglet/gl/base.py", line 334, in destroy
      File "/tmp/gym/.env/lib/python3.5/site-packages/pyglet/gl/xlib.py", line 335, in detach
      File "/tmp/gym/.env/lib/python3.5/site-packages/pyglet/gl/lib.py", line 97, in errcheck
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 887, in _find_spec
    TypeError: 'NoneType' object is not iterable

**Comment by agakshat** [comment]
CartPole-v0 isn't a MuJoCo environment. You should post your issue on the [gym](https://github.com/openai/gym) issue tracker
