### ISSUE TITLE
Could not close renderer for InvertedPendulum-v1: _type_ must have storage info

### ISSUE THREAD

**Issue by hipoglucido** [openai/mujoco-py#24]
I am trying to run some mujoco environments but unfortunately I get this error when I want to render and monitor the video. Any idea?

`[2017-01-04 04:01:05,683] Starting new video recorder writing to /home/hipoglucido/Dropbox/Data_Science/Computational_Cognitive_Neuroscience/project/ddpg-aigym/results/InvertedPendulum-v1False/openaigym.video.0.2957.video000000.mp4
libGL error: unable to load driver: vmwgfx_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: vmwgfx
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
Traceback (most recent call last):
  File "main.py", line 90, in <module>
    main()    
  File "main.py", line 52, in main
    observation = env.reset()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 124, in reset
    observation = self._reset()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/wrappers/monitoring.py", line 29, in _reset
    self._monitor._after_reset(observation)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/monitoring/monitor_manager.py", line 264, in _after_reset
    self._reset_video_recorder()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/monitoring/monitor_manager.py", line 285, in _reset_video_recorder
    self.video_recorder.capture_frame()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/monitoring/video_recorder.py", line 106, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 344, in _render
    return self.env.render(mode, close)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 175, in render
    return self._render(mode=mode, close=close)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 111, in _render
    self._get_viewer().render()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 120, in _get_viewer
    self.viewer.start()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/mujoco_py/mjviewer.py", line 207, in start
    self._init_framebuffer_object()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/mujoco_py/mjviewer.py", line 137, in _init_framebuffer_object
    fbo = gl.glGenFramebuffers(1)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/OpenGL/platform/baseplatform.py", line 407, in __call__
    self.__name__, self.__name__,
OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenFramebuffers, check for bool(glGenFramebuffers) before calling
[2017-01-04 04:01:05,872] Could not close renderer for InvertedPendulum-v1: _type_ must have storage info
[2017-01-04 04:01:05,873] Finished writing results. You can upload them to the scoreboard via gym.upload('/home/hipoglucido/Dropbox/Data_Science/Computational_Cognitive_Neuroscience/project/ddpg-aigym/results/InvertedPendulum-v1False')
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/hipoglucido/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 189, in close
    self.render(close=True)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 166, in render
    return self._render(close=close)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 106, in _render
    self._get_viewer().finish()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/mujoco_py/mjviewer.py", line 325, in finish
    glfw.destroy_window(self.window)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/mujoco_py/glfw.py", line 809, in destroy_window
    window_addr = ctypes.cast(ctypes.pointer(window),
TypeError: _type_ must have storage info
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/hipoglucido/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 189, in close
    self.render(close=True)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/core.py", line 166, in render
    return self._render(close=close)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/gym/envs/mujoco/mujoco_env.py", line 106, in _render
    self._get_viewer().finish()
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/mujoco_py/mjviewer.py", line 325, in finish
    glfw.destroy_window(self.window)
  File "/home/hipoglucido/anaconda2/lib/python2.7/site-packages/mujoco_py/glfw.py", line 809, in destroy_window
    window_addr = ctypes.cast(ctypes.pointer(window),
TypeError: _type_ must have storage info
`

**Comment by tlbtlbtlb** [comment]
> ```
> libGL error: unable to load driver: vmwgfx_dri.so
> libGL error: driver pointer missing
> libGL error: failed to load driver: vmwgfx
> libGL error: unable to load driver: swrast_dri.so
> libGL error: failed to load driver: swrast
> ```

Your OpenGL libraries can't load a renderer. Probably if you run glxgears you'll get similar errors rather than seeing a window with spinning gears.

Depending on your OS, the following may help: http://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update/566522
