### ISSUE TITLE
module 'glfw' has no attribute 'set_error_callback'

### ISSUE THREAD

**Issue by karlzhang-hhg** [openai/mujoco-py#276]
Hi,
I am trying to test my mujoco-py and gym installation. Looks like most of them are correct, except that when I use env.render(), the glfw reports error.

>>> import gym
>>> env = gym.make('Humanoid-v2')
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
>>> env.reset()
array([ 1.39302622e+00,  9.99915478e-01, -6.83082092e-03, -5.25839422e-03,
        9.73272491e-03, -3.62584185e-03,  2.44198029e-03, -3.27250775e-03,
       -8.90267562e-03, -6.78777497e-03, -9.56481988e-03,  3.27340126e-03,
        9.56962742e-04, -7.44154460e-03, -1.61066619e-03, -5.62422119e-03,
       -3.65891827e-03,  1.93642224e-03,  7.55405622e-03,  1.04356438e-03,
        5.59781263e-03,  8.51850577e-03,  2.16168216e-03, -9.01386203e-03,
        2.05939034e-03,  6.44923000e-03, -9.86718904e-03,  8.42595042e-03,
        8.57889429e-03,  2.48967328e-03, -7.09521826e-03, -2.56127030e-03,
       -7.63423839e-03,  9.10454751e-03, -3.30611630e-03,  9.91011990e-03,
        3.98763520e-03,  6.08587078e-03,  2.20186349e-03,  8.21692655e-03,
       -5.65027143e-03,  3.75351617e-03,  5.03364582e-03, -8.09857293e-03,
       -6.07519421e-03,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  2.22851452e+00,
        2.22118370e+00,  3.84426227e-02,  1.79867122e-03,  9.68287528e-02,
       -3.51838202e-02, -1.98065423e-01,  6.73308375e-02,  4.14936639e+00,
        8.32207894e+00,  8.73284250e-02,  8.52679312e-02,  8.99028864e-03,
        2.80711379e-04,  1.14226964e-02, -1.51051760e-03, -5.76364448e-02,
        7.87464498e-03,  4.03484117e-01,  2.03575204e+00,  4.39948320e-02,
        4.25908105e-02,  5.01946053e-02,  4.87525888e-04,  8.91246014e-03,
        4.59952407e-05, -2.70912677e-01,  5.79825081e-03,  1.92624868e-01,
        5.85278711e+00,  2.47200108e-01,  2.04928868e-01,  5.40050040e-02,
       -8.80380089e-03, -1.41642354e-02, -7.79642425e-02, -8.91635090e-02,
       -4.46559499e-01, -7.92314301e-01,  4.52555626e+00,  8.75926271e-01,
        8.47982573e-01,  3.15972390e-02, -2.49978125e-03, -1.28485147e-02,
       -1.52587487e-01, -2.43447852e-02, -2.72337638e-01, -1.46876127e+00,
        2.63249442e+00,  1.03956141e+00,  1.01875805e+00,  2.48203348e-02,
       -6.52548848e-04, -4.55527865e-03, -1.45365742e-01, -6.01131039e-03,
       -1.91829888e-01, -1.33911599e+00,  1.76714587e+00,  2.47149268e-01,
        2.10843789e-01,  4.97291044e-02,  1.01330556e-02, -1.83706953e-02,
        7.20935936e-02, -1.08877719e-01,  4.19143228e-01, -8.06960821e-01,
        4.52555626e+00,  8.74339791e-01,  8.57990301e-01,  2.12326444e-02,
        3.84657519e-03, -2.63536272e-02,  1.18962208e-01, -4.75157086e-02,
        2.12806757e-01, -1.47713160e+00,  2.63249442e+00,  1.03810527e+00,
        1.02798064e+00,  1.49605670e-02,  2.13018444e-03, -2.09776507e-02,
        1.03939320e-01, -2.75634320e-02,  1.36570316e-01, -1.34491847e+00,
        1.76714587e+00,  4.15132994e-01,  3.29236035e-01,  1.09409756e-01,
        2.91087604e-02, -4.11866393e-02,  1.66293991e-01,  1.02553811e-01,
       -3.84621169e-01,  7.06192405e-01,  1.59405984e+00,  3.20008838e-01,
        3.47170122e-01,  1.59352786e-01,  6.99649913e-02, -1.53109351e-01,
        1.19525246e-01,  3.27003635e-01, -2.71216388e-01,  5.46827663e-01,
        1.19834313e+00,  4.19245549e-01,  3.16513596e-01,  1.21423885e-01,
       -2.64355901e-02, -3.31356687e-02, -1.75610605e-01,  8.57294085e-02,
        4.13203226e-01,  6.94107549e-01,  1.59405984e+00,  3.26030092e-01,
        3.31974247e-01,  1.68272966e-01, -7.58613353e-02, -1.45151439e-01,
       -1.32013449e-01,  3.14804156e-01,  3.03837323e-01,  5.36599450e-01,
        1.19834313e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  6.54926893e-03,
       -9.62416889e-03,  8.62746066e-03,  6.63760732e-03, -5.83202665e-03,
        2.21105530e-03,  6.38435227e-03, -7.01939668e-03,  1.71705201e-02,
        5.99261488e-03, -5.62678054e-03,  2.13602488e-03, -7.09052166e-04,
       -7.13281917e-03,  1.70570694e-02,  6.00738480e-03, -6.57481944e-03,
        2.16035158e-03, -3.22445386e-03,  1.73177235e-03,  9.15076247e-03,
        6.83758321e-03, -6.75240757e-03,  1.69711019e-03, -3.25348904e-03,
        5.03666292e-03,  9.06555512e-03,  8.12853492e-03, -6.74235147e-03,
        1.64724676e-03, -3.25348904e-03,  5.03666292e-03,  9.06555512e-03,
        8.12853492e-03, -6.74235147e-03,  1.64724676e-03, -1.06925640e-02,
       -1.27850599e-03,  1.28022300e-02,  5.62878953e-03, -6.60619117e-03,
        3.00551873e-03, -1.06416183e-02, -3.47942091e-03,  1.28419901e-02,
        4.77122618e-03, -6.62531828e-03,  3.04555933e-03, -1.06416183e-02,
       -3.47942091e-03,  1.28419901e-02,  4.77122618e-03, -6.62531828e-03,
        3.04555933e-03,  1.31333061e-02, -2.16586507e-03,  7.94364257e-03,
        2.86530493e-03, -2.41688718e-03,  3.13844864e-03,  1.31483459e-02,
       -4.77536907e-03,  1.06416319e-02,  2.84839793e-03, -2.86383159e-03,
        2.70625680e-03,  1.08530504e-02, -1.73680804e-02,  5.10130512e-03,
        1.00039155e-02, -3.69929017e-03,  1.63596220e-03,  1.07203734e-02,
       -1.30189245e-02,  9.34102495e-03,  1.00752066e-02, -4.38849682e-03,
        2.34518971e-03,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  0.00000000e+00])
>>> env.render()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/rlexp/lib/python3.6/site-packages/gym/core.py", line 284, in render
    return self.env.render(mode)
  File "/anaconda3/envs/rlexp/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 111, in render
    self._get_viewer().render()
  File "/anaconda3/envs/rlexp/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 120, in _get_viewer
    self.viewer = mujoco_py.MjViewer(self.sim)
  File "/Users/kungangzhang/Documents/OneDrive/Northwestern/Study/Courses/DRL_DDPG_SGLD/mujoco-py/mujoco_py/mjviewer.py", line 133, in __init__
    super().__init__(sim)
  File "/Users/kungangzhang/Documents/OneDrive/Northwestern/Study/Courses/DRL_DDPG_SGLD/mujoco-py/mujoco_py/mjviewer.py", line 26, in __init__
    super().__init__(sim)
  File "mujoco_py/mjrendercontext.pyx", line 267, in mujoco_py.cymj.MjRenderContextWindow.__init__
  File "mujoco_py/mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 96, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 44, in mujoco_py.cymj.GlfwContext.__init__
  File "mujoco_py/opengl_context.pyx", line 59, in mujoco_py.cymj.GlfwContext._init_glfw
AttributeError: module 'glfw' has no attribute 'set_error_callback'

Any idea how to fix it? I have search online, but seems no one encounter this before.

**Comment by machinaut** [comment]
What version of `mujoco-py` do you have installed?  What version of `gym` do you have installed?
