### ISSUE TITLE
Windows 10 access=winreg.KEY_READ | winreg.KEY_WOW64_32KEY

### ISSUE THREAD

**Issue by inspirepassion** [openai/mujoco-py#286]
Hello,
I encounter some issues when I:
>>> import mujoco_py

The platform is Windows 10, python==3.5.0
I installed mujoco using: 
pip install mujoco-python==1.50.1.56

Could anyone provide some hint?

The error is shown as bellow:
Compiling C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\cymj.pyx because it changed.
[1/1] Cythonizing C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\cymj.pyx
...
running build_ext
building 'mujoco_py.cymj' extension
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\__init__.py", line 1, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\builder.py", line 468, in <module>
    cymj = load_cython_ext(mjpro_path)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\builder.py", line 90, in load_cython_ext
    cext_so_path = builder.build()
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\builder.py", line 202, in build
    built_so_file_path = self._build_impl()
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\builder.py", line 225, in _build_impl
    dist.run_commands()
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\mujoco_py\builder.py", line 125, in build_extensions
    build_ext.build_extensions(self)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\command\build_ext.py", line 532, in build_extension
    depends=ext.depends)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\_msvccompiler.py", line 315, in compile
    self.initialize()
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\_msvccompiler.py", line 208, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\_msvccompiler.py", line 81, in _get_vc_env
    vcvarsall, vcruntime = _find_vcvarsall(plat_spec)
  File "C:\Users\jason\Anaconda2\envs\p35\lib\distutils\_msvccompiler.py", line 34, in _find_vcvarsall
    access=winreg.KEY_READ | winreg.KEY_WOW64_32KEY
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by machinaut** [comment]
Are you able to compile and run the examples that come with mujoco?

I have not seen this error before, but it looks like it might be an issue with the compiler.

Which compiler are you using?
