### ISSUE TITLE
Failed building wheel for mujoco-py  in ubuntu 18.04.1 LTS

### ISSUE THREAD

**Issue by AchillesRevng** [openai/mujoco-py#315]
~/Downloads/universe-master$ sudo docker build -t universe .
[sudo] password for binu: 
Sending build context to Docker daemon  16.13MB
Step 1/13 : FROM ubuntu:16.04
 ---> 4a689991aa24
Step 2/13 : RUN apt-get update     && apt-get install -y libav-tools     python3-numpy     python3-scipy     python3-setuptools     python3-pip     libpq-dev     libjpeg-dev     curl     cmake     swig     python3-opengl     libboost-all-dev     libsdl2-dev     wget     unzip     git     golang     net-tools     iptables     libvncserver-dev     software-properties-common     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 9766dd98c10c
Step 3/13 : RUN ln -sf /usr/bin/pip3 /usr/local/bin/pip     && ln -sf /usr/bin/python3 /usr/local/bin/python     && pip install -U pip
 ---> Using cache
 ---> 94f10dd521f9
Step 4/13 : RUN pip install gym[all]
 ---> Running in 34701596b729
Collecting gym[all]
  Downloading https://files.pythonhosted.org/packages/c3/44/3a63e8b87f642db49ac81239620e68df8cfae223dcfda4f8508aec88d204/gym-0.10.8.tar.gz (1.5MB)
Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from gym[all]) (0.17.0)
Requirement already satisfied: numpy>=1.10.4 in /usr/lib/python3/dist-packages (from gym[all]) (1.11.0)
Collecting requests>=2.0 (from gym[all])
  Downloading https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl (60kB)
Collecting six (from gym[all])
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting pyglet>=1.2.0 (from gym[all])
  Downloading https://files.pythonhosted.org/packages/1c/fc/dad5eaaab68f0c21e2f906a94ddb98175662cc5a654eee404d59554ce0fa/pyglet-1.3.2-py2.py3-none-any.whl (1.0MB)
Collecting mujoco_py>=1.50 (from gym[all])
  Downloading https://files.pythonhosted.org/packages/cc/1e/0eacaf4fae60a2ba013ed70b61fbf8dbd517bb3be92784dff7a3e4065ad9/mujoco-py-1.50.1.65.tar.gz (119kB)
Collecting imageio (from gym[all])
  Downloading https://files.pythonhosted.org/packages/28/b4/cbb592964dfd71a9de6a5b08f882fd334fb99ae09ddc82081dbb2f718c81/imageio-2.4.1.tar.gz (3.3MB)
Collecting atari_py>=0.1.4 (from gym[all])
  Downloading https://files.pythonhosted.org/packages/16/cc/aabbe1580df0f9b22851e210d5e35e3faa305d10a8783997fb8e79239dbc/atari_py-0.1.6-py3-none-manylinux1_x86_64.whl (1.7MB)
Collecting Pillow (from gym[all])
  Downloading https://files.pythonhosted.org/packages/bc/cc/b6e47b0075ca4267855d77850af7ea4194d2fc591664f1d70e5151b50637/Pillow-5.3.0-cp35-cp35m-manylinux1_x86_64.whl (2.0MB)
Requirement already satisfied: PyOpenGL in /usr/lib/python3/dist-packages (from gym[all]) (3.0.2)
Collecting box2d-py>=2.3.5 (from gym[all])
  Downloading https://files.pythonhosted.org/packages/35/1b/9326661e058e2fbcda2e5b78f58b4406dfb2ae07ae25869cf97e3f708217/box2d_py-2.3.5-cp35-cp35m-manylinux1_x86_64.whl (2.1MB)
Collecting idna<2.8,>=2.5 (from requests>=2.0->gym[all])
  Downloading https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl (58kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0->gym[all])
  Downloading https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.0->gym[all])
  Downloading https://files.pythonhosted.org/packages/8c/4b/5cbc4cb46095f369117dcb751821e1bef9dd86a07c968d8757e9204c324c/urllib3-1.24-py2.py3-none-any.whl (117kB)
Collecting certifi>=2017.4.17 (from requests>=2.0->gym[all])
  Downloading https://files.pythonhosted.org/packages/56/9d/1d02dd80bc4cd955f98980f28c5ee2200e1209292d5f9e9cc8d030d18655/certifi-2018.10.15-py2.py3-none-any.whl (146kB)
Collecting future (from pyglet>=1.2.0->gym[all])
  Downloading https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz (824kB)
Collecting glfw>=1.4.0 (from mujoco_py>=1.50->gym[all])
  Downloading https://files.pythonhosted.org/packages/f3/dd/fd5c662d7a07fca96aaffab585acfa4c624a2400f91a5bc1ebbb514dd4f9/glfw-1.7.0.tar.gz
Collecting Cython>=0.27.2 (from mujoco_py>=1.50->gym[all])
  Downloading https://files.pythonhosted.org/packages/a3/ab/29206c2fd58d62f76f80cfe74f44d0ea8a2733d467693f6bdb0f4c7413ed/Cython-0.29-cp35-cp35m-manylinux1_x86_64.whl (2.0MB)
Collecting cffi>=1.10 (from mujoco_py>=1.50->gym[all])
  Downloading https://files.pythonhosted.org/packages/59/cc/0e1635b4951021ef35f5c92b32c865ae605fac2a19d724fb6ff99d745c81/cffi-1.11.5-cp35-cp35m-manylinux1_x86_64.whl (420kB)
Collecting lockfile>=0.12.2 (from mujoco_py>=1.50->gym[all])
  Downloading https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.10->mujoco_py>=1.50->gym[all])
  Downloading https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz (158kB)
Building wheels for collected packages: gym, mujoco-py, imageio, future, glfw, pycparser
  Running setup.py bdist_wheel for gym: started
  Running setup.py bdist_wheel for gym: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ea/ec/dd/33bcc8801d345f0b640fced8a0864a7c8474828564bc5ccf70
  Running setup.py bdist_wheel for mujoco-py: started
  Running setup.py bdist_wheel for mujoco-py: finished with status 'error'
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tpug7anw/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ajf_7fzq --python-tag cp35:
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-tpug7anw/mujoco-py/setup.py", line 44, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-tpug7anw/mujoco-py/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-tpug7anw/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-tpug7anw/mujoco-py/mujoco_py/builder.py", line 16, in <module>
      from cffi import FFI
  ImportError: No module named 'cffi'
  
  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
  Running setup.py bdist_wheel for imageio: started
  Running setup.py bdist_wheel for imageio: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e0/43/31/605de9372ceaf657f152d3d5e82f42cf265d81db8bbe63cde1
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/bf/c9/a3/c538d90ef17cf7823fa51fc701a7a7a910a80f6a405bf15b1a
  Running setup.py bdist_wheel for glfw: started
  Running setup.py bdist_wheel for glfw: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ca/aa/05/9b802212ed86ef800f54025059bac9e64f58dfaf17fb97e94e
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built gym imageio future glfw pycparser
Failed to build mujoco-py
Installing collected packages: idna, chardet, urllib3, certifi, requests, six, future, pyglet, glfw, Cython, Pillow, imageio, pycparser, cffi, lockfile, mujoco-py, atari-py, box2d-py, gym
  Running setup.py install for mujoco-py: started
    Running setup.py install for mujoco-py: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tpug7anw/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sgircc2p/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tpug7anw/mujoco-py/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-tpug7anw/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-tpug7anw/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-tpug7anw/mujoco-py/mujoco_py/builder.py", line 499, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-install-tpug7anw/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-tpug7anw/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-sgircc2p/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-tpug7anw/mujoco-py/
The command '/bin/sh -c pip install gym[all]' returned a non-zero code: 1

installed mujoco successfully and set the path of license key in ~/.bashrc
can anyone please help me to figure this out

**Comment by machinaut** [comment]
From the error: 
```You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150```

Where did you install mujoco?

I notice the docker build log at the top doesn't have a step to install mujoco.

**Comment by machinaut** [comment]
I made a small dockerfile which demostrates installing mujoco-py and gym[mujoco] on ubuntu 18.04 https://gist.github.com/machinaut/b5a7c6719a30e9fbfd95c13d5e963b61

It works for me, and hopefully will be useful as a reference.

**Comment by binusuresh** [comment]
> From the error:
> `You appear to be missing MuJoCo. We expected to find the file here: /root/.mujoco/mjpro150`
> 
> Where did you install mujoco?
> 
> I notice the docker build log at the top doesn't have a step to install mujoco.

i installed mujoco and it is inside a folder named .mujoco in root itself and inside bashrc i set the path like th export  LD_LIBRARY_PATH=$LD_LIBRARY_PATH:home/***/.mujoco/mjpro150/bin

**Comment by machinaut** [comment]
You can overwrite the default search location with the environment variables MUJOCO_PY_MJPRO_PATH and MUJOCO_PY_MJKEY_PATH 

They're used in this function when searching for the mujoco library https://github.com/openai/mujoco-py/blob/master/mujoco_py/utils.py#L72

I'm confused by your error though, at the top of the issue you have the command `sudo docker build -t universe .`

Are you trying to build an open source project?  Providing a link to it would help me debug it.

**Comment by CHIPI3** [comment]
I have the same problem. Using Mac Sierra:

 Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
  Running setup.py bdist_wheel for imageio: started
  Running setup.py bdist_wheel for imageio: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/e0/43/31/605de9372ceaf657f152d3d5e82f42cf265d81db8bbe63cde1
  Running setup.py bdist_wheel for future: started
  Running setup.py bdist_wheel for future: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/fc/5b/ec/2983c4a6e3692d1315f44d6480c6abdd8585d96471b431d6b4
  Running setup.py bdist_wheel for glfw: started
  Running setup.py bdist_wheel for glfw: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/ca/aa/05/9b802212ed86ef800f54025059bac9e64f58dfaf17fb97e94e
  Running setup.py bdist_wheel for pycparser: started
  Running setup.py bdist_wheel for pycparser: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built gym imageio future glfw pycparser
Failed to build mujoco-py
Installing collected packages: urllib3, certifi, chardet, idna, requests, six, future, pyglet, glfw, Cython, Pillow, imageio, pycparser, cffi, lockfile, mujoco-py, box2d-py, atari-py, gym
  Running setup.py install for mujoco-py: started
    Running setup.py install for mujoco-py: finished with status 'error'
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-s_s3unmi/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-ggylc1xf/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-s_s3unmi/mujoco-py/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.5/distutils/command/install.py", line 583, in run
        self.run_command('build')
      File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-s_s3unmi/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-s_s3unmi/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-s_s3unmi/mujoco-py/mujoco_py/builder.py", line 499, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-install-s_s3unmi/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
Any help?

**Comment by machinaut** [comment]
@CHIPI3 it looks like you are incorrectly running the command as the root user.

```You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150```

We look in the home directory of the user you install as (which the install instructions say to put mujoco).

If you want to run install as a root user, then you need to install mujoco to the root user's home directory.

I believe you probably do not want to install as the root user.

**Comment by CHIPI3** [comment]
Thank you Alex. Would you be so kind to tell me which steps to follow then if I do not want to install as the root user? I am pretty new to this, so if you can give me some basic instructions I would appreciate it. I do not understand this sentence you are using very clearly: "We look in the home directory of the user you install as (which the install instructions say to put mujoco)"

**Comment by CHIPI3** [comment]
the instructions in Github are: Unzip the downloaded mjpro150 directory into ~/.mujoco/mjpro150, and place your license key (the mjkey.txt file from your email) at ~/.mujoco/mjkey.txt. But actually I can download mjpro150 already unzipped. Then, how do I create a /.mujoco/ folder? Just using terminal and typing mkdir? then I just drag mjpro150 and mjkey.txt to that folder? How do I install mujoco-py from my terminal into /root/.mujoco/mjpro150? I mean, I am pretty new to this so if you can guide me through some basic steps it would be great. thanks!

**Comment by CHIPI3** [comment]
I mean, when i do pip install mujoco-py, to which folder is mujoco-py installed by default? Sorry to ask you so basic questions here.

**Comment by Gishnumohan** [comment]
Is this issue solved? even im facing same problem
