### ISSUE TITLE
Errors while installing into a new conda env

### ISSUE THREAD

**Issue by omry** [openai/mujoco-py#342]
**Describe the bug**
While installing into a conda env, there are errors about missing packages, which results in some kind of recovery which eventually correctly installs.
This is confusing to users.

**To Reproduce**
$ conda create -n test -y python=3.6
$ source activate test
$ pip install mujoco-py

**Expected behavior**
Installation of pip packages should not produce user facing errors. dependencies should be installed before mujoco-py is installed.

**Error Messages**
$ pip install mujoco-py
Collecting mujoco-py
  Using cached https://files.pythonhosted.org/packages/cf/8c/64e0630b3d450244feef0688d90eab2448631e40ba6bdbd90a70b84898e7/mujoco-py-1.50.1.68.tar.gz
Collecting glfw>=1.4.0 (from mujoco-py)
Collecting numpy>=1.11 (from mujoco-py)
  Using cached https://files.pythonhosted.org/packages/7b/74/54c5f9bb9bd4dae27a61ec1b39076a39d359b3fb7ba15da79ef23858a9d8/numpy-1.16.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting Cython>=0.27.2 (from mujoco-py)
  Using cached https://files.pythonhosted.org/packages/da/27/cd9476b91f01522b76edb4feff752f3a8be7d26d709be6707abbaace99d3/Cython-0.29.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting imageio>=2.1.2 (from mujoco-py)
Collecting cffi>=1.10 (from mujoco-py)
  Using cached https://files.pythonhosted.org/packages/6d/c0/47db8f624f3e4e2f3f27be03a93379d1ba16a1450a7b1aacfa0366e2c0dd/cffi-1.11.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting lockfile>=0.12.2 (from mujoco-py)
  Using cached https://files.pythonhosted.org/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting pillow (from imageio>=2.1.2->mujoco-py)
  Using cached https://files.pythonhosted.org/packages/85/5e/e91792f198bbc5a0d7d3055ad552bc4062942d27eaf75c3e2783cf64eae5/Pillow-5.4.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.10->mujoco-py)
Building wheels for collected packages: mujoco-py
  Running setup.py bdist_wheel for mujoco-py ... error
  Complete output from command /private/home/omry/.conda/envs/test/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-q94z9nh4/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-e9bx3jj3 --python-tag cp36:
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-q94z9nh4/mujoco-py/setup.py", line 44, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/private/home/omry/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/private/home/omry/.conda/envs/test/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/private/home/omry/.conda/envs/test/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/private/home/omry/.conda/envs/test/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/private/home/omry/.conda/envs/test/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/private/home/omry/.conda/envs/test/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/private/home/omry/.conda/envs/test/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-q94z9nh4/mujoco-py/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-q94z9nh4/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-q94z9nh4/mujoco-py/mujoco_py/builder.py", line 15, in <module>
      import numpy as np
  ModuleNotFoundError: No module named 'numpy'

  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: glfw, numpy, Cython, pillow, imageio, pycparser, cffi, lockfile, mujoco-py
  Running setup.py install for mujoco-py ... done
Successfully installed Cython-0.29.3 cffi-1.11.5 glfw-1.7.0 imageio-2.4.1 lockfile-0.12.2 mujoco-py-1.50.1.68 numpy-1.16.0 pillow-5.4.1 pycparser-2.19

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Anaconda3/5.0.1
 - Python Version 3.6 in Anaconda.
 - Mujoco : I have both 131 and 150 installed, I don't think mujoco-py actually uses them at this stage.
 - mujoco-py version :  mujoco-py-1.50.1.68

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`
/public/apps/anaconda3/5.0.1/lib:/public/slurm/18.08.4/lib:/private/home/omry/.mujoco/mjpro150/bin

 - output of: `echo $HOME`
/private/home/omry

 - output of: `echo $USER`
omry

**Comment by omry** [comment]
this is actually specific to this somewhat old version of conda and seems okay in newer versions.
closing.
