### ISSUE TITLE
OSError when using MjViewer.start()

### ISSUE THREAD

**Issue by xiaoguai0992** [openai/mujoco-py#39]
I found there is a problem with MjViewer.start(). 
 I'm using win10 with python3.6.1
```python
import mujoco_py as mj

m = mj.MjModel("humanoid.xml")
v = mj.MjViewer()
v.set_model(m)
v.start()
```

Then error occurred:
```
Traceback (most recent call last): 
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\lib\site-packages\mujoco_py\mjviewer.py", line 180, in start _, _, refresh_rate = glfw.get_video_mode(glfw.get_primary_monitor()) 
  File "C:\Anaconda3\lib\site-packages\mujoco_py\glfw.py", line 719, in get_video_mode videomode = _glfw.glfwGetVideoMode(monitor).contents 
OSError: exception: access violation reading 0x0000000000000078
```
I don't know what the problem is and how to solve this.

**Comment by xiaoguai0992** [comment]
Oh I just found that the problem is caused by remote desktop.
When the error occurred, I was using remote desktop on windows.
I use it on the origin machine directly, then it works well.
