### ISSUE TITLE
LD_LIBRARY_PATH Error

### ISSUE THREAD

**Issue by Rowing0914** [openai/mujoco-py#409]
**Describe the bug**
From PyCharm, (from terminal it is WORKING), I could not get to work this simple script below due to the lack of `path to your environment variable`. But honestly, I have no clue how to solve this. I mean, mujoco requires me to set two different values to the `LD_LIBRARY_PATH`, so it occurred me that might be a bug-ish.

**To Reproduce**
```python
import os
# os.environ["LD_LIBRARY_PATH"] = "$LD_LIBRARY_PATH:/home/username/.mujoco/mujoco200/bin"
# print(os.environ["LD_LIBRARY_PATH"])
os.environ["LD_LIBRARY_PATH"] = "$LD_LIBRARY_PATH:/usr/lib/nvidia-410"
print(os.environ["LD_LIBRARY_PATH"])

import gym
env = gym.make('Hopper-v2')
env.reset()
for _ in range(5000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

""" Error MSG
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-410
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/my_username/.mujoco/mujoco200/bin
```

```python

/usr/local/bin/python3.6 /home/username/Desktop/path/path/path/mujoco_test.py
$LD_LIBRARY_PATH:/home/username/.mujoco/mujoco200/bin
Traceback (most recent call last):
  File "/home/username/Desktop/path/path/path/mujoco_test.py", line 8, in <module>
    env = gym.make('Hopper-v2')
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 123, in make
    env = spec.make(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 86, in make
    cls = load(self._entry_point)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/registration.py", line 14, in load
    result = entry_point.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/gym/envs/mujoco/__init__.py", line 1, in <module>
    from gym.envs.mujoco.mujoco_env import MujocoEnv
  File "/usr/local/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 11, in <module>
    import mujoco_py
  File "/home/username/Desktop/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/username/Desktop/mujoco-py/mujoco_py/builder.py", line 503, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/username/Desktop/mujoco-py/mujoco_py/builder.py", line 71, in load_cython_ext
    _ensure_set_env_var("LD_LIBRARY_PATH", get_nvidia_lib_dir())
  File "/home/username/Desktop/mujoco-py/mujoco_py/builder.py", line 118, in _ensure_set_env_var
    var_name, var_name, lib_path))
Exception: 
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/username/.mujoco/mujoco200/bin
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-410

Process finished with exit code 1


""" Error MSG
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/username/.mujoco/mujoco200/bin
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia-410

"""
```

**Expected behavior**
When I run below in the directory cloned from  Git repo of `mujoco-py`

```python

import gym
env = gym.make('Hopper-v2')
env.reset()
for _ in range(5000):
    env.render()
    env.step(env.action_space.sample()) # take a random action

""" === this works fine! === """
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04.6 LTS(xenial)
 - Python Version: 3.6.6
 - Mujoco Version: 2.0
 - mujoco-py version
```shell
>>> import mujoco_py
>>> mujoco_py.__version__
'2.0.2.0'
```

**Comment by Rowing0914** [comment]
Sorry, I could solve this issue myself by setting env variables through the configuration of Pycharm so that I'd close this issue.
