### ISSUE TITLE
LD_LIBRARY_PATH error during install

### ISSUE THREAD

**Issue by OnesoulKang** [openai/mujoco-py#421]
**Describe the bug**
I'm trying to install this package but I have a problem related to LD_LIBRARY_PATH.

**To Reproduce**
1. I installed MuJoCo and I run /.simulate. It was fine.
2. I tried to install 'Gym' via `sudo -H pip install -e .[all]`
3. and I got error with LD_LIBRARY_PATH.
4. I added `    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/onesoulkang/.mujoco/mujoco200/bin` to my bashrc.
5. I checked whether it registered or not via `echo $LD_LIBRARY_PATH`.
`/home/onesoulkang/catkin_ws/devel/lib:/opt/ros/melodic/lib:/usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe:/root/.mujoco/mujoco200/bin`
6. I tried to install again.
7. Still got same error.

**Error Messages**
```
Collecting mujoco-py
  Using cached https://files.pythonhosted.org/packages/a9/c8/daac2e747a0a516f6a880bf73304bd58e18d8be5cea926e8a1e5938026e6/mujoco-py-2.0.2.2.tar.gz
Requirement already satisfied: glfw>=1.4.0 in /usr/local/lib/python3.6/dist-packages (from mujoco-py) (1.8.1)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.6/dist-packages (from mujoco-py) (1.16.2)
Requirement already satisfied: Cython>=0.27.2 in /usr/local/lib/python3.6/dist-packages (from mujoco-py) (0.29.10)
Requirement already satisfied: imageio>=2.1.2 in /usr/local/lib/python3.6/dist-packages (from mujoco-py) (2.5.0)
Requirement already satisfied: cffi>=1.10 in /usr/local/lib/python3.6/dist-packages (from mujoco-py) (1.12.3)
Requirement already satisfied: lockfile>=0.12.2 in /usr/local/lib/python3.6/dist-packages (from mujoco-py) (0.12.2)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from imageio>=2.1.2->mujoco-py) (5.1.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.10->mujoco-py) (2.19)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-uu8ojyre/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-zut7lvf8 --python-tag cp36:
  ERROR: running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-uu8ojyre/mujoco-py/setup.py", line 45, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-uu8ojyre/mujoco-py/setup.py", line 29, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/builder.py", line 503, in <module>
      cymj = load_cython_ext(mujoco_path)
    File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/builder.py", line 69, in load_cython_ext
      _ensure_set_env_var("LD_LIBRARY_PATH", lib_path)
    File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/builder.py", line 118, in _ensure_set_env_var
      var_name, var_name, lib_path))
  Exception:
  Missing path to your environment variable.
  Current values LD_LIBRARY_PATH=/root/.mujoco/mujoco200/bin
  Please add following line to .bashrc:
  export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/onesoulkang/.mujoco/mujoco200/bin
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Running setup.py install for mujoco-py ... error
    ERROR: Complete output from command /usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-uu8ojyre/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-din7azz8/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-uu8ojyre/mujoco-py/setup.py", line 45, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-uu8ojyre/mujoco-py/setup.py", line 29, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/builder.py", line 503, in <module>
        cymj = load_cython_ext(mujoco_path)
      File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/builder.py", line 69, in load_cython_ext
        _ensure_set_env_var("LD_LIBRARY_PATH", lib_path)
      File "/tmp/pip-install-uu8ojyre/mujoco-py/mujoco_py/builder.py", line 118, in _ensure_set_env_var
        var_name, var_name, lib_path))
    Exception:
    Missing path to your environment variable.
    Current values LD_LIBRARY_PATH=/root/.mujoco/mujoco200/bin
    Please add following line to .bashrc:
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/onesoulkang/.mujoco/mujoco200/bin
    ----------------------------------------
ERROR: Command "/usr/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-uu8ojyre/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-din7azz8/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-uu8ojyre/mujoco-py/
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Python Version : 2.7.15+ and 3.6.8
 - Mujoco Version : MuJoCo 2.0
 - mujoco-py version : 

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`
`/home/onesoulkang/catkin_ws/devel/lib:/opt/ros/melodic/lib:/usr/lib/mesa-diverted/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/mesa:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/x86_64-linux-gnu/gallium-pipe:/root/.mujoco/mujoco200/bin`
 - output of: `echo $HOME`
`/home/onesoulkang`
 - output of: `echo $USER`
`onesoulkang`

**Comment by nlnjnj** [comment]
OS: Ubuntu 18.04
Python Version : 3.6.9
Mujoco Version : MuJoCo 2.0
mujoco-py version : 2.0.2.5

I came across the same issue, then I run the following command:
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MUJOCO_PY_MUJOCO_PATH/bin`

after that I got this error:
`Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting mujoco-py>=2.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/31/85/57a2a6ed8356100f2eff1678976187dff9ebc1d059af4664ada06f4bb424/mujoco-py-2.0.2.5.tar.gz (769kB)
     |████████████████████████████████| 778kB 2.2MB/s 
Requirement already satisfied, skipping upgrade: glfw>=1.4.0 in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from mujoco-py>=2.0) (1.8.3)
Requirement already satisfied, skipping upgrade: numpy>=1.11 in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from mujoco-py>=2.0) (1.14.5)
Requirement already satisfied, skipping upgrade: Cython>=0.27.2 in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from mujoco-py>=2.0) (0.29.13)
Requirement already satisfied, skipping upgrade: imageio>=2.1.2 in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from mujoco-py>=2.0) (2.5.0)
Requirement already satisfied, skipping upgrade: cffi>=1.10 in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from mujoco-py>=2.0) (1.12.3)
Requirement already satisfied, skipping upgrade: lockfile>=0.12.2 in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from mujoco-py>=2.0) (0.12.2)
Requirement already satisfied, skipping upgrade: pillow in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from imageio>=2.1.2->mujoco-py>=2.0) (6.1.0)
Requirement already satisfied, skipping upgrade: pycparser in /home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages (from cffi>=1.10->mujoco-py>=2.0) (2.19)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/googolple/.conda/envs/cambricon/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-zxoxcvd3/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-zxoxcvd3/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-pzccpuyx --python-tag cp36
       cwd: /tmp/pip-install-zxoxcvd3/mujoco-py/
  Complete output (22 lines):
  running bdist_wheel
  running build
  Removing old mujoco_py cext /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/cymj_2.0.2.5_36_linuxcpuextensionbuilder_36.so
  Compiling /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/cymj.pyx because it changed.
  [1/1] Cythonizing /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/cymj.pyx
  running build_ext
  building 'mujoco_py.cymj' extension
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3/mujoco-py
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/gl
  gcc -pthread -B /home/googolple/.conda/envs/cambricon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py -I/home/googolple/PycharmProjects/cambricon/mujoco200/include -I/home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages/numpy/core/include -I/home/googolple/.conda/envs/cambricon/include/python3.6m -c /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/cymj.o -fopenmp -w
  gcc -pthread -B /home/googolple/.conda/envs/cambricon/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Imujoco_py -I/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py -I/home/googolple/PycharmProjects/cambricon/mujoco200/include -I/home/googolple/.conda/envs/cambricon/lib/python3.6/site-packages/numpy/core/include -I/home/googolple/.conda/envs/cambricon/include/python3.6m -c /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/gl/osmesashim.c -o /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6
  creating /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py
  gcc -pthread -shared -B /home/googolple/.conda/envs/cambricon/compiler_compat -L/home/googolple/.conda/envs/cambricon/lib -Wl,-rpath=/home/googolple/.conda/envs/cambricon/lib -Wl,--no-as-needed -Wl,--sysroot=/ /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/cymj.o /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/gl/osmesashim.o -L/home/googolple/PycharmProjects/cambricon/mujoco200/bin -Wl,-R/home/googolple/PycharmProjects/cambricon/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /tmp/pip-install-zxoxcvd3/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
  /home/googolple/.conda/envs/cambricon/compiler_compat/ld: cannot find -lGL
  collect2: error: ld returned 1 exit status
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
`
