### ISSUE TITLE
Exception: Please add mujoco library to your PATH in Windows 64bit

### ISSUE THREAD

**Issue by kibamin** [openai/mujoco-py#451]
I installed mujoco_py on python3.7 and windows 10 64bit successfully
But when `import mujoco_py` get this error :

> Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\learning\MS\RL\codes\mujoco\env\lib\site-packages\mujoco_py-2.0.2.5-py3.7.egg\mujoco_py\__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "C:\Program Files\JetBrains\PyCharm 2018.1.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 19, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "D:\learning\MS\RL\codes\mujoco\env\lib\site-packages\mujoco_py-2.0.2.5-py3.7.egg\mujoco_py\builder.py", line 507, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "D:\learning\MS\RL\codes\mujoco\env\lib\site-packages\mujoco_py-2.0.2.5-py3.7.egg\mujoco_py\builder.py", line 79, in load_cython_ext
    "set %s=%s;%%%s%%" % (var, lib_path, var))
**Exception: Please add mujoco library to your PATH:
set PATH=C:\Users\Amin\.mujoco\mujoco200\bin;%PATH%**

I set PATH but take same error again :|

how to fix this error?

**Comment by chinmaySwami** [comment]
I was getting a similar error. I am using the path variables MUJOCO_PY_MJKEY_PATH and MUJOCO_PY_MUJOCO_PATH
So for MJKEY variable i set the mujoco200\bin\  path while  for MUJOCO path i set mujoco200\ path
I stopped getting the error above however i am getting a new error which says cannot 
"Could not open activation key file C:\mujoco\mujoco200\bin\mjkey.txt"

So the main problem is because you are not setting the path correctly for the key and for MUJOCO

**Comment by gokriznastic** [comment]
@chinmaySwami doing this doesn't solve the issue for my end. I am stuck installing mujoco. Please help.

**Comment by kushantp58** [comment]
Even I'm facing this error....Can somebody please help..

**Comment by chinmaySwami** [comment]
For windows, We need to create these environment variables under system variables at the same time we also have to add the path C:\Users\Amin.mujoco\mujoco200\bin to the path variable 

NOTE : We do not need the MJKEY variable anymore since mujoco was acquired by deepmind and was made free.

**Comment by Omar-Abdul-Aziz** [comment]
@chinmaySwami I'm using python3 in window 10 and I don't know how to add and solve the PARTH problem. Can you please be more specific?

**Comment by Omar-Abdul-Aziz** [comment]
@chinmaySwami  can I do it without using Ubuntu? If so, can you please help to do so?

**Comment by suhibalobeidat** [comment]
add the key to your bin directory

**Comment by ChristopherHerneth** [comment]
For those of you having issues installing under windows 10:
Try this guide: https://medium.com/@sayanmndl21/install-openai-gym-with-box2d-and-mujoco-in-windows-10-e25ee9b5c1d5
I had to alter the following things to get it to work:

**1:**
Setting the Path variables:
Close the PowerShell (the variables will only be active when you re-open the shell)
go to the environment variables:
Systemvariables - new
name : MUJOCO_PY_MJKEY_PATH
value : C:\YOUR_PATH\.mujoco\mjkey.txt  # as previosly stated this might not be necessary

and another one 
Systemvariables - new
name : MUJOCO_PY_MUJOCO_PATH
value : C:\YOUR_PATH\.mujoco\mjpro150 # not the bin folder!

then under systemvariables - Path - new
C:\YOUR_PATH\.mujoco\mjpro150\bin # bin folder

**2:**
> conda install -c anaconda git #install git
> git clone https://github.com/openai/mujoco-py.git #clone mujoco-py
> cd mujoco-py
> **git checkout 9ea9bb000d** # Windows support has been DEPRECATED and removed in [2.0.2.0](https://github.com/openai/mujoco-py/releases/tag/v2.0.2.0a1). One known good past version is [1.50.1.68](https://github.com/openai/mujoco-py/blob/9ea9bb000d6b8551b99f9aa440862e0c7f7b4191/README.md#requirements).
> python -m pip install --upgrade setuptools #upgrade setuptools
> pip install -r requirements.txt #install requirements
> pip install -r requirements.dev.txt #install dev requirements

the rest I did exactly as in the guide. 
You can test the install with the suggested FetchReach env.
I had to install 
pip install gym-robotics
to make that one work
