### ISSUE TITLE
Can't import in VSCode Debugger

### ISSUE THREAD

**Issue by fiorenza2** [openai/mujoco-py#479]
**Describe the bug**
Trying to run the VSCode Debugger causes it to hang, and is caused whenever I try to import anything related to Mujoco-py (i.e., `mujoco-py` or `gym.envs.mujoco`).
This has only happened recently, it was previously working well.

**To Reproduce**
* Create a new `.py` file with `import mujoco_py`
* Debugger won't do anything, and hangs at the import

**Expected behavior**
That the debugger is able to get past the import and debug the code.

**Error Messages**
Pressing Ctrl+C during the hanging in the terminal produces the following:

```
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 74, in <module>
    main()
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 37, in main
    adapter.channel.wait()
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1231, in wait
    parser_thread.join()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
(rp1env) bash-3.2$ env PTVSD_SESSION_ID=1 PTVSD_LAUNCHER_PORT=52291 /Users/philipball/Envs/rp1env/bin/python /Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher /Users/philipball/Documents/Code/ReadyPolicy1/env_aug.py --env_name HalfCheetah-v2 --model_epochs 100 --initial 300 --policy_iters 30 --model_epochs 2000 --no_reward_head --update_timestep 200 --steps 100 
^CTraceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd/pydevd.py", line 2515, in settrace
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 74, in <module>
    main()
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/__main__.py", line 37, in main
    adapter.channel.wait()
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/launcher/../../ptvsd/common/messaging.py", line 1231, in wait
    ide_access_token,
  File "/Users/philipball/.vscode/extensions/ms-python.python-2019.11.49689/pythonFiles/lib/python/new_ptvsd/wheels/ptvsd/_vendored/pydevd/pydevd.py", line 2602, in _locked_settrace
    time.sleep(0.1)  # busy wait until we receive run command
KeyboardInterrupt
    parser_thread.join()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1044, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 1060, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
```

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6
 - Python Version 3.7.5
 - Mujoco Version 1.50 and 2.00
 - mujoco-py version 1.50.1.56, 1.50.1.59, 2.0.2.8

**Additional context**
* Only mujoco-py related packages cause this in my debugger
* This has only happened recently, it was working fine previously
* I initially thought it was a lockfile issue, but installing an old version of mujoco-py which didn't have lockfiles hasn't addressed anything
* I have tried various uninstalls, reinstalls, different Mujoco versions. Also have tried reinstalling VS Code.
* mujoco-py imports in everything else, including the integrated terminal inside VS Code

**Comment by fiorenza2** [comment]
Workaround, but not built-in terminal: https://code.visualstudio.com/docs/python/debugging#_attach-to-a-local-script

**Comment by fiorenza2** [comment]
Workaround; uninstall VSCode fully, switch over to Insiders + Python Insiders.

**Comment by fiorenza2** [comment]
Closing as this hasn't happened again, but may re-open if it pops up.
