### ISSUE TITLE
Failed building wheel on macOS Catalina

### ISSUE THREAD

**Issue by vittorione94** [openai/mujoco-py#480]
**Describe the bug**
Failed building wheel on macOS Catalina

**To Reproduce**
pip install -U 'mujoco-py<2.1,>=2.0'

**Error Messages**

Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py'"'"'; __file__='"'"'/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-wheel-VPtUBr --python-tag cp27
       cwd: /private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/
  Complete output (28 lines):
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py", line 45, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py", line 29, in run
      import mujoco_py  # noqa: force build
    File "mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "mujoco_py/builder.py", line 495
      print(MISSING_KEY_MESSAGE.format(key_path), file=sys.stderr)
                                                      ^
  SyntaxError: invalid syntax
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
    Running setup.py install for mujoco-py ... error
    ERROR: Command errored out with exit status 1:
     command: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py'"'"'; __file__='"'"'/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-record-4KLEVU/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/
    Complete output (30 lines):
    running install
    running build
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py", line 45, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/Library/Python/2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/Library/Python/2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 573, in run
        self.run_command('build')
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py", line 29, in run
        import mujoco_py  # noqa: force build
      File "mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "mujoco_py/builder.py", line 495
        print(MISSING_KEY_MESSAGE.format(key_path), file=sys.stderr)
                                                        ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py'"'"'; __file__='"'"'/private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-install-V2N5cq/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bn/8_w5077s1js81pyyw8qy6gv00000gn/T/pip-record-4KLEVU/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.1
 - Python 2.7.16

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`
/Users/vittorio/.mujoco/mujoco200/bin
 - output of: `echo $HOME`
/Users/vittorio
 - output of: `echo $USER`
vittorio

**Additional context**

**Comment by ZhenhuiTang** [comment]
Did you solved this problem？
