### ISSUE TITLE
You appear to be missing MuJoCo.  We expected to find the file here: /home/zhao/.mujoco/mjpro150

### ISSUE THREAD

**Issue by zhaoworking** [openai/mujoco-py#491]
Exception:You appear to be missing MuJoCo.  We expected to find the file here: /home/zhao/.mujoco/mjpro150
 error :Failed building wheel for mujoco-py

Obtaining file:///home/zhao/gym
Requirement already satisfied: scipy in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: numpy>=1.10.4 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: six in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: pyglet<=1.3.2,>=1.2.0 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: cloudpickle~=1.2.0 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: opencv-python in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: atari_py~=0.2.0 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: Pillow in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: box2d-py~=2.3.5 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Collecting mujoco_py<2.0,>=1.50 (from gym==0.15.4)
  Using cached https://files.pythonhosted.org/packages/cf/8c/64e0630b3d450244feef0688d90eab2448631e40ba6bdbd90a70b84898e7/mujoco-py-1.50.1.68.tar.gz
Requirement already satisfied: imageio in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from gym==0.15.4)
Requirement already satisfied: future in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from pyglet<=1.3.2,>=1.2.0->gym==0.15.4)
Requirement already satisfied: glfw>=1.4.0 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from mujoco_py<2.0,>=1.50->gym==0.15.4)
Requirement already satisfied: Cython>=0.27.2 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from mujoco_py<2.0,>=1.50->gym==0.15.4)
Requirement already satisfied: cffi>=1.10 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from mujoco_py<2.0,>=1.50->gym==0.15.4)
Requirement already satisfied: lockfile>=0.12.2 in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from mujoco_py<2.0,>=1.50->gym==0.15.4)
Requirement already satisfied: pycparser in /home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages (from cffi>=1.10->mujoco_py<2.0,>=1.50->gym==0.15.4)
Building wheels for collected packages: mujoco-py
  Running setup.py bdist_wheel for mujoco-py ... error
  Complete output from command /home/zhao/Downloads/usr/anaconda3/envs/gymlab/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pitkxn97/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpy4s32b0upip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  
  You appear to be missing MuJoCo.  We expected to find the file here: /home/zhao/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-pitkxn97/mujoco-py/setup.py", line 44, in <module>
      tests_require=read_requirements_file('requirements.dev.txt'),
    File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-pitkxn97/mujoco-py/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-build-pitkxn97/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-build-pitkxn97/mujoco-py/mujoco_py/builder.py", line 502, in <module>
      mjpro_path, key_path = discover_mujoco()
    File "/tmp/pip-build-pitkxn97/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
      raise Exception(message)
  Exception:
  You appear to be missing MuJoCo.  We expected to find the file here: /home/zhao/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  
  ----------------------------------------
  Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py, gym
  Running setup.py install for mujoco-py ... error
    Complete output from command /home/zhao/Downloads/usr/anaconda3/envs/gymlab/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-pitkxn97/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-wdk42scy-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /home/zhao/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pitkxn97/mujoco-py/setup.py", line 44, in <module>
        tests_require=read_requirements_file('requirements.dev.txt'),
      File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/zhao/Downloads/usr/anaconda3/envs/gymlab/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-pitkxn97/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-build-pitkxn97/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-build-pitkxn97/mujoco-py/mujoco_py/builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-build-pitkxn97/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /home/zhao/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    

when i test the mojoco_py,and it remind me that " We expected to find the file here: /home/zhao/.mujoco/mjpro150".But when i test "pip install -e '.[all]'",it remind me "We expected to find the file here: /home/zhao/.mujoco/mojoco200".Actually mojoco_py works well,but when it goes to gum install,the Exception :You appear to be missing MuJoCo will appear.
I have got confused that how  to set the envs path.

**Comment by zhaoworking** [comment]
I choose another system operation called Ubuntu16.4,and it has works well right now.Incidentally,the problem occurred at CentOs7 system operation doesn't happen.
