### ISSUE TITLE
libmujoco200.dylib Library Validation error in macOS Catalina

### ISSUE THREAD

**Issue by lubaroli** [openai/mujoco-py#496]
**Describe the bug**
Fresh install of Mujoco on macOS Catalina fails as libmujoco200.dylib is unable to load due to Library Validation.

**To Reproduce**
brew install gcc
pip install mujoco-py

OR

brew install gcc
git clone https://github.com/openai/mujoco-py.git
pip install -e ~/mujoco-py
python -c "import mujoco_py"

**Expected behavior**
Successfully install and load module.

**Error Messages**
_When using pip install_:
```
$ pip install mujoco-py
Collecting mujoco-py
  Using cached https://files.pythonhosted.org/packages/a2/30/21abd0cf2734bf5f34a7a8967789b12dee55f1e51e9c1c60af1cba549123/mujoco-py-2.0.2.9.tar.gz
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for mujoco-py from https://files.pythonhosted.org/packages/a2/30/21abd0cf2734bf5f34a7a8967789b12dee55f1e51e9c1c60af1cba549123/mujoco-py-2.0.2.9.tar.gz#sha256=6ae20ca9509203758f5e30a7a4019cb2d581b6d40dc2c2669dbe3229cfdf05e8.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Requirement already satisfied: cffi>=1.10 in /usr/local/lib/python3.7/site-packages (from mujoco-py) (1.13.2)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.7/site-packages (from mujoco-py) (1.17.4)
Requirement already satisfied: Cython>=0.27.2 in /usr/local/lib/python3.7/site-packages (from mujoco-py) (0.29.14)
Requirement already satisfied: imageio>=2.1.2 in /usr/local/lib/python3.7/site-packages (from mujoco-py) (2.6.1)
Requirement already satisfied: fasteners~=0.15 in /usr/local/lib/python3.7/site-packages (from mujoco-py) (0.15)
Requirement already satisfied: glfw>=1.4.0 in /usr/local/lib/python3.7/site-packages (from mujoco-py) (1.8.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.7/site-packages (from cffi>=1.10->mujoco-py) (2.19)
Requirement already satisfied: pillow in /usr/local/lib/python3.7/site-packages (from imageio>=2.1.2->mujoco-py) (6.2.1)
Requirement already satisfied: six in /usr/local/lib/python3.7/site-packages (from fasteners~=0.15->mujoco-py) (1.13.0)
Requirement already satisfied: monotonic>=0.1 in /usr/local/lib/python3.7/site-packages (from fasteners~=0.15->mujoco-py) (1.5)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python/bin/python3.7 /usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/tmpvmxq8gm4
       cwd: /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py
  Complete output (70 lines):
  running bdist_wheel
  running build
  Removing old mujoco_py cext /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/cymj_2.0.2.9_37_macextensionbuilder_37.so
  Compiling /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/cymj.pyx because it depends on /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/Cython/Includes/numpy/__init__.pxd.
  [1/1] Cythonizing /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/cymj.pyx
  running build_ext
  building 'mujoco_py.cymj' extension
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/gl
  /usr/local/bin/gcc-9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DONMAC -Imujoco_py -I/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py -I/Users/lubaroli/.mujoco/mujoco200/include -I/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/cymj.c -o /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/cymj.o -fopenmp -w
  /usr/local/bin/gcc-9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DONMAC -Imujoco_py -I/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py -I/Users/lubaroli/.mujoco/mujoco200/include -I/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/gl/dummyshim.c -o /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/gl/dummyshim.o -fopenmp -w
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/lib.macosx-10.15-x86_64-3.7
  creating /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/lib.macosx-10.15-x86_64-3.7/mujoco_py
  /usr/local/bin/gcc-9 -bundle -undefined dynamic_lookup /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/cymj.o /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/gl/dummyshim.o -L/Users/lubaroli/.mujoco/mujoco200/bin -L/Users/lubaroli/.mujoco/mujoco200/bin -lmujoco200 -lglfw.3 -o /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/lib.macosx-10.15-x86_64-3.7/mujoco_py/cymj.cpython-37m-darwin.so -fopenmp
  Traceback (most recent call last):
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 182, in build_wheel
      metadata_directory)
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 209, in build_wheel
      wheel_directory, config_settings)
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 237, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 51, in <module>
      'Programming Language :: Python :: 3 :: Only',
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-build-env-_2bnq5ro/normal/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 29, in run
      import mujoco_py  # noqa: force build
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/builder.py", line 510, in <module>
      cymj = load_cython_ext(mujoco_path)
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/builder.py", line 106, in load_cython_ext
      mod = load_dynamic_ext('cymj', cext_so_path)
    File "/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/builder.py", line 125, in load_dynamic_ext
      return loader.load_module()
  ImportError: dlopen(/private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/cymj_2.0.2.9_37_macextensionbuilder_37.so, 2): Library not loaded: /Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib
    Referenced from: /private/var/folders/fx/hg3qwzrd3l5cq1mxc62thsdm0000gn/T/pip-install-oy37gbwz/mujoco-py/mujoco_py/generated/cymj_2.0.2.9_37_macextensionbuilder_37.so
    Reason: no suitable image found.  Did find:
  	/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib: code signature in (/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
  	/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib: code signature in (/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
ERROR: Could not build wheels for mujoco-py which use PEP 517 and cannot be installed directly
```
_When building from source:_
```
$ python -c "import mujoco_py"
Compiling /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/cymj.pyx because it changed.
[1/1] Cythonizing /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/cymj.pyx
running build_ext
building 'mujoco_py.cymj' extension
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/gl
/usr/local/bin/gcc-9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DONMAC -I/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py -I/Users/lubaroli/.mujoco/mujoco200/include -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/cymj.c -o /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/cymj.o -fopenmp -w
/usr/local/bin/gcc-9 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DONMAC -I/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py -I/Users/lubaroli/.mujoco/mujoco200/include -I/usr/local/lib/python3.7/site-packages/numpy/core/include -I/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/gl/dummyshim.c -o /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/gl/dummyshim.o -fopenmp -w
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/lib.macosx-10.15-x86_64-3.7
creating /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/lib.macosx-10.15-x86_64-3.7/mujoco_py
/usr/local/bin/gcc-9 -bundle -undefined dynamic_lookup /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/cymj.o /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/temp.macosx-10.15-x86_64-3.7/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/gl/dummyshim.o -L/Users/lubaroli/.mujoco/mujoco200/bin -L/Users/lubaroli/.mujoco/mujoco200/bin -lmujoco200 -lglfw.3 -o /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.9_37_macextensionbuilder/lib.macosx-10.15-x86_64-3.7/mujoco_py/cymj.cpython-37m-darwin.so -fopenmp
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/builder.py", line 510, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/builder.py", line 106, in load_cython_ext
    mod = load_dynamic_ext('cymj', cext_so_path)
  File "/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/builder.py", line 125, in load_dynamic_ext
    return loader.load_module()
ImportError: dlopen(/Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/cymj_2.0.2.9_37_macextensionbuilder_37.so, 2): Library not loaded: /Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib
  Referenced from: /Users/lubaroli/Dropbox (Sydney Uni)/Dev/mujoco-py/mujoco_py/generated/cymj_2.0.2.9_37_macextensionbuilder_37.so
  Reason: no suitable image found.  Did find:
	/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib: code signature in (/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
	/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib: code signature in (/Users/lubaroli/.mujoco/mujoco200/bin/libmujoco200.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
```

**Desktop (please complete the following information):**
 - OS: [macOS 10.15.2]
 - Python Version [3.7.5]
 - Mujoco Version [mujoco200]
 - mujoco-py version [mujoco-py-2.0.2.9]

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`

 - output of: `echo $HOME`
/Users/lubaroli
 - output of: `echo $USER`
lubaroli

**Additional context**
When building from source, there is no error during the installation, only when first imported by python.

**Comment by amolchanov86** [comment]
Helped me
https://github.com/hashicorp/terraform/issues/23033#issuecomment-543507812

**Comment by lubaroli** [comment]
> Helped me: you need to give access to the Terminal in Security & Privacy under System Preferences, and then run the command in Terminal after restarting it:
> [hashicorp/terraform#23033 (comment)](https://github.com/hashicorp/terraform/issues/23033#issuecomment-543507812)

Thank you! That solved the problem!
