### ISSUE TITLE
MacOS: unable to install mujoco_pyj the way it is described and libglfw.3.dylib disallowed by system policy

### ISSUE THREAD

**Issue by shufflebyte** [openai/mujoco-py#502]
Did not find an issue for that, so I open a new one to share my solution with you. Maybe it helps someone.

**Describe the bug**
Followed installation instructions in README.md for installing MuJoCo version 2 for OSX, but did not work. It appears that mujoco_py 1.5 is installed instead of mujoco_py 2. Cannot verify that I did not do something wrong before.

**To Reproduce**
- Download the MuJoCo version 2.0 binaries for Linux or OSX.
- Unzip the downloaded mujoco200 directory into ~/.mujoco/mujoco200, and place your license key (the mjkey.txt file from your email) at ~/.mujoco/mjkey.txt.
Then run
```
python
import mujoco_py
```

**Expected behavior**
I expected that it includes my mujoco_py in version 2 but instead got the error message.

**Error Messages**
```
>>> import mujoco_py
You appear to be missing MuJoCo.  We expected to find the file here: /Users/florian/.mujoco/mjpro150
(...)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/florian/anaconda3/envs/tf2/lib/python3.7/site-packages/mujoco_py-1.50.1.68-py3.7.egg/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/Users/florian/anaconda3/envs/tf2/lib/python3.7/site-packages/mujoco_py-1.50.1.68-py3.7.egg/mujoco_py/builder.py", line 502, in <module>
    mjpro_path, key_path = discover_mujoco()
  File "/Users/florian/anaconda3/envs/tf2/lib/python3.7/site-packages/mujoco_py-1.50.1.68-py3.7.egg/mujoco_py/utils.py", line 93, in discover_mujoco
    raise Exception(message)
Exception:
You appear to be missing MuJoCo.  We expected to find the file here: /Users/florian/.mujoco/mjpro150
(...)
```

**Desktop (please complete the following information):**
 - OS: macOS 10.15.2
 - Python Version 3.7.5
 - Anaconda: conda 4.7.12
 - Mujoco Version 200
 - mujoco-py version 1.50.1.68

**Environment**
 - output of: `echo $LD_LIBRARY_PATH` is not set. Everything to default.

**Additional context**

**Solution**
I cloned the repository and installed it manually with `pip install -e .`. Then for Catalina users it will probably fail and output errors with following in it:
```
/Users/florian/.mujoco/mujoco200/bin/libglfw.3.dylib: code signature in (/Users/florian/.mujoco/mujoco200/bin/libglfw.3.dylib) not valid for use in process using Library Validation: library load disallowed by system policy
```
This can be solved by telling gatekeeper to ignore ~/.mujoco.
`xattr -r -d com.apple.quarantine .mujoco` from your `/Users/`folder.
After fixing it, you might try again `pip install -e .` and it should run.

I tested with the instrunctions in README.md where it says `To play with mujoco-py interactively, follow these steps:`.

**Conclusion**
I think the first error is related to mujoco_py. The second error (while solving the first error for me) might be related to mujoco itself. I hope I could help someone, who got same problems.

**Comment by LXYYY** [comment]
A simple hack to solve this unverified problem, is to open the folder in finder, and right-click -> open anything that's not verified. And then confirm to open in the pop up window. Then it's considered verified
