### ISSUE TITLE
Cannot install mujoco

### ISSUE THREAD

**Issue by Hsgngr** [openai/mujoco-py#540]
**Describe the bug**
I am following the readme, I have the keys however cannot install it.

**To Reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**Error Messages**
```
(ubuntuSpinningUp) wisestrider@Strider:~/mujoco-py$ ENV LD_LIBRARY_PATH $LD_LIBRARY_PATH:/root/.mujoco/mjpro150/bin
ENV: command not found
(ubuntuSpinningUp) wisestrider@Strider:~/mujoco-py$ RUN pip3 install gym[mujoco]
RUN: command not found
(ubuntuSpinningUp) wisestrider@Strider:~/mujoco-py$ pip3 install gym[mujoco]
Collecting gym[mujoco]
  Downloading gym-0.17.2.tar.gz (1.6 MB)
     |████████████████████████████████| 1.6 MB 762 kB/s
Collecting cloudpickle<1.4.0,>=1.2.0
  Downloading cloudpickle-1.3.0-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: numpy>=1.10.4 in /home/wisestrider/.local/lib/python3.8/site-packages (from gym[mujoco]) (1.18.4)
Collecting pyglet<=1.5.0,>=1.4.0
  Using cached pyglet-1.5.0-py2.py3-none-any.whl (1.0 MB)
Collecting scipy
  Downloading scipy-1.4.1-cp38-cp38-manylinux1_x86_64.whl (26.0 MB)
     |████████████████████████████████| 26.0 MB 274 kB/s
Requirement already satisfied: imageio in /home/wisestrider/.local/lib/python3.8/site-packages (from gym[mujoco]) (2.8.0)
Collecting mujoco_py<2.0,>=1.50
  Using cached mujoco-py-1.50.1.68.tar.gz (120 kB)
Collecting future
  Using cached future-0.18.2.tar.gz (829 kB)
Requirement already satisfied: pillow in /home/wisestrider/.local/lib/python3.8/site-packages (from imageio->gym[mujoco]) (7.1.2)
Requirement already satisfied: Cython>=0.27.2 in /home/wisestrider/.local/lib/python3.8/site-packages (from mujoco_py<2.0,>=1.50->gym[mujoco]) (0.29.19)
Requirement already satisfied: cffi>=1.10 in /home/wisestrider/.local/lib/python3.8/site-packages (from mujoco_py<2.0,>=1.50->gym[mujoco]) (1.14.0)
Requirement already satisfied: glfw>=1.4.0 in /home/wisestrider/.local/lib/python3.8/site-packages (from mujoco_py<2.0,>=1.50->gym[mujoco]) (1.11.1)
Collecting lockfile>=0.12.2
  Using cached lockfile-0.12.2-py2.py3-none-any.whl (13 kB)
Requirement already satisfied: pycparser in /home/wisestrider/.local/lib/python3.8/site-packages (from cffi>=1.10->mujoco_py<2.0,>=1.50->gym[mujoco]) (2.20)
Building wheels for collected packages: gym, mujoco-py, future
  Building wheel for gym (setup.py) ... done
  Created wheel for gym: filename=gym-0.17.2-py3-none-any.whl size=1650892 sha256=9d163607e49447fdc61f1ba4a019a7cb0eb12b4764cf7f676d36536424e71514
  Stored in directory: /home/wisestrider/.cache/pip/wheels/48/bf/7c/44b1b8e4ad998fc48e31caedbb9e028351861b8d20632642bc
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xnkxkplm/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xnkxkplm/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-uaa70ju_
       cwd: /tmp/pip-install-xnkxkplm/mujoco-py/
  Complete output (27 lines):
  running bdist_wheel
  running build
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-xnkxkplm/mujoco-py/setup.py", line 32, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-xnkxkplm/mujoco-py/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-xnkxkplm/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-xnkxkplm/mujoco-py/mujoco_py/builder.py", line 20, in <module>
      from lockfile import LockFile
  ModuleNotFoundError: No module named 'lockfile'
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=040c8ead6f65c7fbc140c6fdf4edccc8aec92243b062f5523407b766161ee95c
  Stored in directory: /home/wisestrider/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
Successfully built gym future
Failed to build mujoco-py
Installing collected packages: cloudpickle, future, pyglet, scipy, lockfile, mujoco-py, gym
  Attempting uninstall: mujoco-py
    Found existing installation: mujoco-py 2.0.2.10
    Uninstalling mujoco-py-2.0.2.10:
      Successfully uninstalled mujoco-py-2.0.2.10
    Running setup.py install for mujoco-py ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xnkxkplm/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xnkxkplm/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-f69k2vh9/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/wisestrider/.local/include/python3.8/mujoco-py
         cwd: /tmp/pip-install-xnkxkplm/mujoco-py/
    Complete output (56 lines):
    running install
    running build

    You appear to be missing MuJoCo.  We expected to find the file here: /home/wisestrider/.mujoco/mjpro150

    This package only provides python bindings, the library must be installed separately.

    Please follow the instructions on the README to install MuJoCo

        https://github.com/openai/mujoco-py#install-mujoco

    Which can be downloaded from the website

        https://www.roboti.us/index.html

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xnkxkplm/mujoco-py/setup.py", line 32, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-xnkxkplm/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-xnkxkplm/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-xnkxkplm/mujoco-py/mujoco_py/builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-install-xnkxkplm/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /home/wisestrider/.mujoco/mjpro150

    This package only provides python bindings, the library must be installed separately.

    Please follow the instructions on the README to install MuJoCo

        https://github.com/openai/mujoco-py#install-mujoco

    Which can be downloaded from the website

        https://www.roboti.us/index.html
```
**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.13.6]
 - Python Version [e.g. 3.6.6]
 - Mujoco Version 150
 - mujoco-py version

**Environment**
 - output of: `echo $LD_LIBRARY_PATH = Nothing`
 - output of: `echo $HOME` = /home/wisestrider
 - output of: `echo $USER` = wisestrider

**Additional context**

**Comment by arvind32** [comment]
I was using the **mujoco200_macos** zip version and got the same issue. To resolve I had to

1. Change the name to **mujoco200** (removing the suffix)
2. Move the unzipped folder to the path mentioned: _/home/wisestrider/.mujoco/_ (In my user home folder I basically created a folder called _mujoco_, saved the unzipped folder there and changed the name in terminal to _.mujoco_; I also copied the token file to be in the path _/home/wisestrider/.mujoco/_)
3. Re-attempt and it should work (but you may still get other errors)
