### ISSUE TITLE
libglfw.3.dylib exists in 2 locations

### ISSUE THREAD

**Issue by vusirikala** [openai/mujoco-py#590]
I installed mujoco-py via
```
pip3 install mujoco-py==2.0.2.9
```

However when I import mujoco_py, I get this error. 
```
>>> import mujoco_py
objc[7772]: Class GLFWApplicationDelegate is implemented in both /Users/satya/.mujoco/mujoco200/bin/libglfw.3.dylib (0x119530778) and /usr/local/lib/python3.9/site-packages/glfw/libglfw.3.dylib (0x1196576e8). One of the two will be used. Which one is undefined.
objc[7772]: Class GLFWWindowDelegate is implemented in both /Users/satya/.mujoco/mujoco200/bin/libglfw.3.dylib (0x119530700) and /usr/local/lib/python3.9/site-packages/glfw/libglfw.3.dylib (0x119657710). One of the two will be used. Which one is undefined.
objc[7772]: Class GLFWContentView is implemented in both /Users/satya/.mujoco/mujoco200/bin/libglfw.3.dylib (0x1195307a0) and /usr/local/lib/python3.9/site-packages/glfw/libglfw.3.dylib (0x119657760). One of the two will be used. Which one is undefined.
objc[7772]: Class GLFWWindow is implemented in both /Users/satya/.mujoco/mujoco200/bin/libglfw.3.dylib (0x119530818) and /usr/local/lib/python3.9/site-packages/glfw/libglfw.3.dylib (0x1196577d8). One of the two will be used. Which one is undefined.
```

I tried removing the glfw files from mujoco library via
```
rm /Users/satya/.mujoco/mujoco200/bin/libglfw*
```

Now when I import mujoco_py library, I get this error
```
>>> import mujoco_py
Import error. Trying to rebuild mujoco_py.
running build_ext
building 'mujoco_py.cymj' extension
/usr/local/bin/gcc-8 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DONMAC -I/usr/local/lib/python3.9/site-packages/mujoco_py -I/Users/satya/.mujoco/mujoco200/include -I/usr/local/lib/python3.9/site-packages/numpy/core/include -I/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /usr/local/lib/python3.9/site-packages/mujoco_py/cymj.c -o /usr/local/lib/python3.9/site-packages/mujoco_py/generated/_pyxbld_2.0.2.9_39_macextensionbuilder/temp.macosx-10.15-x86_64-3.9/usr/local/lib/python3.9/site-packages/mujoco_py/cymj.o -fopenmp -w
/usr/local/bin/gcc-8 -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -DONMAC -I/usr/local/lib/python3.9/site-packages/mujoco_py -I/Users/satya/.mujoco/mujoco200/include -I/usr/local/lib/python3.9/site-packages/numpy/core/include -I/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c /usr/local/lib/python3.9/site-packages/mujoco_py/gl/dummyshim.c -o /usr/local/lib/python3.9/site-packages/mujoco_py/generated/_pyxbld_2.0.2.9_39_macextensionbuilder/temp.macosx-10.15-x86_64-3.9/usr/local/lib/python3.9/site-packages/mujoco_py/gl/dummyshim.o -fopenmp -w
/usr/local/bin/gcc-8 -bundle -undefined dynamic_lookup -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk /usr/local/lib/python3.9/site-packages/mujoco_py/generated/_pyxbld_2.0.2.9_39_macextensionbuilder/temp.macosx-10.15-x86_64-3.9/usr/local/lib/python3.9/site-packages/mujoco_py/cymj.o /usr/local/lib/python3.9/site-packages/mujoco_py/generated/_pyxbld_2.0.2.9_39_macextensionbuilder/temp.macosx-10.15-x86_64-3.9/usr/local/lib/python3.9/site-packages/mujoco_py/gl/dummyshim.o -L/Users/satya/.mujoco/mujoco200/bin -L/Users/satya/.mujoco/mujoco200/bin -lmujoco200 -lglfw.3 -o /usr/local/lib/python3.9/site-packages/mujoco_py/generated/_pyxbld_2.0.2.9_39_macextensionbuilder/lib.macosx-10.15-x86_64-3.9/mujoco_py/cymj.cpython-39-darwin.so -fopenmp
ld: library not found for -lglfw.3
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 204, in link
    self.spawn(linker + ld_args)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 87, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/local/bin/gcc-8' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/builder.py", line 510, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/builder.py", line 335, in _build_impl
    so_file_path = super()._build_impl()
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/local/lib/python3.9/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 551, in build_extension
    self.compiler.link_shared_object(
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 713, in link_shared_object
    self.link(CCompiler.SHARED_OBJECT, objects,
  File "/usr/local/Cellar/python@3.9/3.9.0_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 206, in link
    raise LinkError(msg)
distutils.errors.LinkError: command '/usr/local/bin/gcc-8' failed with exit code 1
```

I tried putting back libglfw* files into mujoco library and uninstalled glfw library via ```pip3 uninstall glfw```. Now, I get the following error instead. 

```
>>> import mujoco_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/__init__.py", line 6, in <module>
    from mujoco_py.mjviewer import MjViewer, MjViewerBasic
  File "/usr/local/lib/python3.9/site-packages/mujoco_py/mjviewer.py", line 2, in <module>
    import glfw
ModuleNotFoundError: No module named 'glfw'
```

Please help me out. What mistake am I doing?

**Comment by JobJob** [comment]
A good workaround is here: https://github.com/openai/mujoco-py/issues/495#issuecomment-685135364

Basically you want the versions in the `~/.mujoco/mujoco/mujocoXXX/bin` directory to just be symlinks to the ones in your `/path/to/site-packages/glfw` directory

note you can skip step 1 because the path to the lib file in your site-packages is in the error message:
```
>>> import mujoco_py
objc[7772]: Class GLFWApplicationDelegate is implemented in both /Users/satya/.mujoco/mujoco200/bin/libglfw.3.dylib (0x119530778) and /usr/local/lib/python3.9/site-packages/glfw/libglfw.3.dylib (0x1196576e8). One of the two will be used. Which one is undefined.
...
```

so for you the fix is:
```
$ cd ~/.mujoco/mujoco200/bin
~/.mujoco/mujoco200/bin $ mv libglfw.3.dylib libglfw.3.dylib.unused
~/.mujoco/mujoco200/bin $ ln -s /usr/local/lib/python3.9/site-packages/glfw/libglfw.3.dylib
```

See the limitations of this solution at the bottom of https://github.com/openai/mujoco-py/issues/495#issuecomment-685135364
