### ISSUE TITLE
Difference behavior between running in terminal vs in Pycharm

### ISSUE THREAD

**Issue by jing-bi** [openai/mujoco-py#602]
**Describe the bug**
mujoco-py is installed in a conda environment, execute the same command with same environment variables
everything works fine in ternimal.
BUT when i use pycharm, it seems cannot find the **libglewegl.so** lib:
```shell
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/u/user/miniconda3/envs/vplan/lib/python3.8/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/u/user/miniconda3/envs/vplan/lib/python3.8/site-packages/mujoco_py/builder.py", line 515, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/u/user/miniconda3/envs/vplan/lib/python3.8/site-packages/mujoco_py/builder.py", line 103, in load_cython_ext
    mod = load_dynamic_ext('cymj', cext_so_path)
  File "/u/user/miniconda3/envs/vplan/lib/python3.8/site-packages/mujoco_py/builder.py", line 128, in load_dynamic_ext
    module=loader.load_module()
ImportError: libglewegl.so: cannot open shared object file: No such file or directory
```
I tried to modify the source code and `print(name,path)` in `load_dynamic_ext` in mujoco-py/builder.py.
Both method give me the same result which is
`cymj /u/user/miniconda3/envs/vplan/lib/python3.8/site-packages/mujoco_py/generated/cymj_2.0.2.13_38_linuxgpuextensionbuilder_38.so
`
but once executed `loader.load_module()`, pycharm will say `ImportError: libglewegl.so: cannot open shared object file: No such file or directory` while things work well in terminal.

**Desktop (please complete the following information):**
 - OS: Linux 16.04
 - Mujoco Version: 200

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`:'/u/user/.mujoco/mujoco200/bin:/usr/lib/nvidia-440'

**Comment by tiny-vla** [comment]
me too, anybody help!!!!!!

**Comment by hbonnavaud** [comment]
For some reason in pycharm, you should set the LD_LIBRARY_PATH variable in another way (yeah, it pissed me off too.)

### For a script

Add the LD_LIBRARY_PATH value in the pycharm run configuration:
 - Can be accessed in the top-right after you run your code, click on it then click on "edit configuration"
![image](https://github.com/openai/mujoco-py/assets/45778095/06bd9fc4-3d96-4450-b959-3f63e6dd4676)
 - Or can be accessed by right-click on the file to launch > "edit run/debug configurations" 

then add your environment variable here 
![image](https://github.com/openai/mujoco-py/assets/45778095/c4674bab-e8f7-4b8e-83b1-8bf1856e4307)

### For pycharm python console
do the same but here
![image](https://github.com/openai/mujoco-py/assets/45778095/f5b81574-b855-4dc8-9927-74e773c815ca)
