### ISSUE TITLE
Installing mujoco-py in a container that uses GPU for rendering?

### ISSUE THREAD

**Issue by Amir-Arsalan** [openai/mujoco-py#614]
I followed the steps described in #523 and #408 to built a container with `mujoco-py` installed in it that uses GPUs for rendering. However, when do `import mujoco_py` I get the following errors when `mujoco-py` is trying to create some files/directories that is needed for rendering with GPUs. However, it is not possible to create any files inside the container after the it is built as the file system becomes read-only, except if those files are going to be stored in `/tmp`. Also, in my case it is not an option to build the container as writable. Is there a way to either change the path where those files are going to be created or keep those files in memory?

```
import mujoco_py
running build_ext
building 'mujoco_py.cymj' extension
creating /usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/generated/_pyxbld_2.0.2.13_37_linuxgpuextensionbuilder
Traceback (most recent call last):
  File "/usr/lib/python3.7/distutils/dir_util.py", line 70, in mkpath
    os.mkdir(head, mode)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/generated/_pyxbld_2.0.2.13_37_linuxgpuextensionbuilder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/builder.py", line 510, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/builder.py", line 291, in _build_impl
    so_file_path = super()._build_impl()
  File "/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.7/dist-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/usr/local/lib/python3.7/dist-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 566, in compile
    depends, extra_postargs)
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 348, in _setup_compile
    self.mkpath(os.path.dirname(obj))
  File "/usr/lib/python3.7/distutils/ccompiler.py", line 916, in mkpath
    mkpath(name, mode, dry_run=self.dry_run)
  File "/usr/lib/python3.7/distutils/dir_util.py", line 74, in mkpath
    "could not create '%s': %s" % (head, exc.args[-1]))
distutils.errors.DistutilsFileError: could not create '/usr/local/lib/python3.7/dist-packages/mujoco_py-2.0.2.13-py3.7.egg/mujoco_py/generated/_pyxbld_2.0.2.13_37_linuxgpuextensionbuilder': Read-only file system

```

**Comment by SpencerSzabados** [comment]
Not sure if anyone cares about this issue anymore considering its rather stale, but I figured I would post my hack for getting around this (common) error when dealing with singularity containers.

One way of fixing this, if you can't launch the container in a writable state (system dependent), is to bind the paths mojoco_py will write files into and export those paths explicitly as environment variables when you run the container. If you are on a slurm based system you can use the temporary job storage or a dedicated external folder for this acting as a temp file. 

For example, your container launch can look something like this

```bash
CONTAINER_PATH="/containers/mujoco.sif"
CONDA_PATH="/opt/conda/envs/dpa/bin:/opt/conda/bin"
SITE_GEN="/opt/conda/envs/dpa/lib/python3.10/site-packages/mujoco_py/generated"

# Job-local temp dirs for writable generated and mujoco cache
TMP_ROOT="${SLURM_TMPDIR:-$(mktemp -d)}"
TMP_GEN="$TMP_ROOT/mujoco_generated"
TMP_CACHE="$TMP_ROOT/mujoco_cache"
mkdir -p "$TMP_GEN" "$TMP_CACHE"

# Copy required includes into temp generated
singularity exec --nv \
  --env PATH="$CONDA_PATH:$PATH" \
  --bind "$TMP_GEN:/work_gen" \
  "$CONTAINER_PATH" \
  bash -lc "cp -a '$SITE_GEN/.' /work_gen/"

# GPU EGL envs: prefer container GLVND/EGL, select NVIDIA
EGL_ENV=(
    --env MUJOCO_GL=osmesa
    --env PYOPENGL_PLATFORM=osmesa
    --env MUJOCO_EGL_DEVICE=0
    --env __GLX_VENDOR_LIBRARY_NAME=nvidia
    --env EGL_PLATFORM=device
    --env LD_LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/usr/local/cuda/lib64:$LD_LIBRARY_PATH"
    --env LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/env/mujoco210/bin
    --env PATH="$CONDA_PATH:$PATH"
)

# Run pipeline with GPU + EGL
singularity exec --nv \
    --bind "$TMP_GEN:$SITE_GEN" \
    --bind "$TMP_CACHE:/mujoco_cache" \
    --env MUJOCO_PY_CACHE_DIR=/mujoco_cache \
    "${EGL_ENV[@]}" \
    "$CONTAINER_PATH" \
    python train.py
```
