### ISSUE TITLE
Import error, "cannot find -lmujoco200 -lglewosmesa"

### ISSUE THREAD

**Issue by namansaxena9** [openai/mujoco-py#628]
**Describe the bug**
While running "import mujoco_py" statement, I am getting error message "cannot find -lmujoco200 -lglewosmesa". Hence not able to successfully import mujoco_py

**To Reproduce**
Run "import mujoco_py" in python.

**Expected behavior**
Failed import of package

**Error Messages**
>>> import mujoco_py
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /home/namansaxena/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/namansaxena/mujoco-py/mujoco_py -I/home/namansaxena/.mujoco/mujoco200/include -I/home/namansaxena/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/home/namansaxena/anaconda3/include/python3.8 -c /home/namansaxena/mujoco-py/mujoco_py/cymj.c -o /home/namansaxena/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxcpuextensionbuilder/temp.linux-x86_64-3.8/home/namansaxena/mujoco-py/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /home/namansaxena/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/namansaxena/mujoco-py/mujoco_py -I/home/namansaxena/.mujoco/mujoco200/include -I/home/namansaxena/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/home/namansaxena/anaconda3/include/python3.8 -c /home/namansaxena/mujoco-py/mujoco_py/gl/osmesashim.c -o /home/namansaxena/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxcpuextensionbuilder/temp.linux-x86_64-3.8/home/namansaxena/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
gcc -pthread -shared -B /home/namansaxena/anaconda3/compiler_compat -L/home/namansaxena/anaconda3/lib -Wl,-rpath=/home/namansaxena/anaconda3/lib -Wl,--no-as-needed -Wl,--sysroot=/ /home/namansaxena/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxcpuextensionbuilder/temp.linux-x86_64-3.8/home/namansaxena/mujoco-py/mujoco_py/cymj.o /home/namansaxena/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxcpuextensionbuilder/temp.linux-x86_64-3.8/home/namansaxena/mujoco-py/mujoco_py/gl/osmesashim.o -L/home/namansaxena/.mujoco/mujoco200/bin -Wl,-R/home/namansaxena/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /home/namansaxena/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.13_38_linuxcpuextensionbuilder/lib.linux-x86_64-3.8/mujoco_py/cymj.cpython-38-x86_64-linux-gnu.so -fopenmp
/home/namansaxena/anaconda3/compiler_compat/ld: cannot find -lmujoco200
/home/namansaxena/anaconda3/compiler_compat/ld: cannot find -lglewosmesa
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/spawn.py", line 157, in _spawn_posix
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/namansaxena/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/namansaxena/mujoco-py/mujoco_py/builder.py", line 510, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/namansaxena/mujoco-py/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/namansaxena/mujoco-py/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/home/namansaxena/mujoco-py/mujoco_py/builder.py", line 273, in _build_impl
    so_file_path = super()._build_impl()
  File "/home/namansaxena/mujoco-py/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/namansaxena/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/namansaxena/mujoco-py/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/home/namansaxena/anaconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial    self.build_extension(ext)
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/command/build_ext.py", line 550, in build_extension
    self.compiler.link_shared_object(
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/ccompiler.py", line 713, in link_shared_object
    self.link(CCompiler.SHARED_OBJECT, objects,
  File "/home/namansaxena/anaconda3/lib/python3.8/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

**Desktop (please complete the following information):**
I am using remote GPU server
 - OS: CentOS 7
 - Python Version : 3.8.8
 - Mujoco Version 2.0
 - mujoco-py version 2.0.2.5

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`
 /opt/opempi/lib:/home/namansaxena/.mujoco/mujoco200/bin
 - output of: `echo $HOME`
 /home/namansaxena
 - output of: `echo $USER`
 namansaxena

**Additional context**
I have already installed packages like : 1)mesa-libOSMesa-devel  2)mesa-libGL-devel 3)mesa-libGLU-devel 4)mesa-libGL 5)glfw

**Comment by miercat0424** [comment]
How did you solve this problem?

**Comment by namansaxena9** [comment]
It turned out I was using windows version of Mujoco on CentOS. I downloaded the linux version and it started working.
