### ISSUE TITLE
Issue with installing gym[atari] to use its environments

### ISSUE THREAD

**Issue by amirmahdiKhosravi** [openai/mujoco-py#639]
**_I tried to install both gym[atari] and gym[all], but I get the following errors: 
(I think there should be some problem with mujoco and box2d-py)_**

`(base) amir@Khosi:~$ sudo pip install gym[all]

Processing /root/.cache/pip/wheels/27/6d/b3/a3a6e10704795c9b9000f1ab2dc480dfe7bed42f5972806e73/gym-0.21.0-py3-none-any.whl
Requirement already satisfied: cloudpickle>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from gym[all]) (2.0.0)
Requirement already satisfied: numpy>=1.18.0 in /usr/lib/python3/dist-packages (from gym[all]) (1.18.4)
Requirement already satisfied: lz4>=3.1.0; extra == "all" in /usr/local/lib/python3.8/dist-packages (from gym[all]) (3.1.3)
Requirement already satisfied: opencv-python>=3.; extra == "all" in /usr/local/lib/python3.8/dist-packages (from gym[all]) (4.5.3.56)
Requirement already satisfied: pyglet>=1.4.0; extra == "all" in /usr/local/lib/python3.8/dist-packages (from gym[all]) (1.5.21)
Requirement already satisfied: ale-py~=0.7.1; extra == "all" in /usr/local/lib/python3.8/dist-packages (from gym[all]) (0.7.2)
Requirement already satisfied: scipy>=1.4.1; extra == "all" in /usr/lib/python3/dist-packages (from gym[all]) (1.5.2)
Processing /root/.cache/pip/wheels/8b/95/16/1dc99ff9a3f316ff245fdb5c9086cd13c35dad630809909075/box2d_py-2.3.5-cp38-cp38-linux_x86_64.whl
Collecting mujoco-py<2.0,>=1.50; extra == "all"
  Using cached mujoco-py-1.50.1.68.tar.gz (120 kB)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.8/dist-packages (from ale-py~=0.7.1; extra == "all"->gym[all]) (5.2.2)
Requirement already satisfied: Cython>=0.27.2 in /usr/local/lib/python3.8/dist-packages/Cython-3.0.0a9-py3.8-linux-x86_64.egg (from mujoco-py<2.0,>=1.50; extra == "all"->gym[all]) (3.0.0a9)
Requirement already satisfied: cffi>=1.10 in /usr/local/lib/python3.8/dist-packages/cffi-1.15.0-py3.8-linux-x86_64.egg (from mujoco-py<2.0,>=1.50; extra == "all"->gym[all]) (1.15.0)
Requirement already satisfied: glfw>=1.4.0 in /usr/local/lib/python3.8/dist-packages/glfw-2.3.0-py3.8-linux-x86_64.egg (from mujoco-py<2.0,>=1.50; extra == "all"->gym[all]) (2.3.0)
Requirement already satisfied: imageio>=2.1.2 in /usr/local/lib/python3.8/dist-packages/imageio-2.9.0-py3.8.egg (from mujoco-py<2.0,>=1.50; extra == "all"->gym[all]) (2.9.0)
Requirement already satisfied: lockfile>=0.12.2 in /usr/lib/python3/dist-packages (from mujoco-py<2.0,>=1.50; extra == "all"->gym[all]) (0.12.2)
Requirement already satisfied: zipp>=3.1.0; python_version < "3.10" in /usr/local/lib/python3.8/dist-packages (from importlib-resources->ale-py~=0.7.1; extra == "all"->gym[all]) (3.6.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.8/dist-packages/pycparser-2.20-py3.8.egg (from cffi>=1.10->mujoco-py<2.0,>=1.50; extra == "all"->gym[all]) (2.20)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from imageio>=2.1.2->mujoco-py<2.0,>=1.50; extra == "all"->gym[all]) (7.2.0)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-br238456/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-br238456/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-2indcd_z
       cwd: /tmp/pip-install-br238456/mujoco-py/
  Complete output (54 lines):
  running bdist_wheel
  running build
  
  You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-br238456/mujoco-py/setup.py", line 32, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-br238456/mujoco-py/setup.py", line 28, in run
      import mujoco_py  # noqa: force build
    File "/tmp/pip-install-br238456/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/tmp/pip-install-br238456/mujoco-py/mujoco_py/builder.py", line 502, in <module>
      mjpro_path, key_path = discover_mujoco()
    File "/tmp/pip-install-br238456/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
      raise Exception(message)
  Exception:
  You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
  
  This package only provides python bindings, the library must be installed separately.
  
  Please follow the instructions on the README to install MuJoCo
  
      https://github.com/openai/mujoco-py#install-mujoco
  
  Which can be downloaded from the website
  
      https://www.roboti.us/index.html
  
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: box2d-py, mujoco-py, gym
    Running setup.py install for mujoco-py ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-br238456/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-br238456/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zx88kh17/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/mujoco-py
         cwd: /tmp/pip-install-br238456/mujoco-py/
    Complete output (56 lines):
    running install
    running build
    
    You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-br238456/mujoco-py/setup.py", line 32, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 163, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-br238456/mujoco-py/setup.py", line 28, in run
        import mujoco_py  # noqa: force build
      File "/tmp/pip-install-br238456/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
        from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
      File "/tmp/pip-install-br238456/mujoco-py/mujoco_py/builder.py", line 502, in <module>
        mjpro_path, key_path = discover_mujoco()
      File "/tmp/pip-install-br238456/mujoco-py/mujoco_py/utils.py", line 93, in discover_mujoco
        raise Exception(message)
    Exception:
    You appear to be missing MuJoCo.  We expected to find the file here: /root/.mujoco/mjpro150
    
    This package only provides python bindings, the library must be installed separately.
    
    Please follow the instructions on the README to install MuJoCo
    
        https://github.com/openai/mujoco-py#install-mujoco
    
    Which can be downloaded from the website
    
        https://www.roboti.us/index.html
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-br238456/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-br238456/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zx88kh17/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.8/mujoco-py Check the logs for full command output.`

**Comment by zpeng1997** [comment]
well, you need to install mujoco-py manually
