### ISSUE TITLE
mujoco_py set path

### ISSUE THREAD

**Issue by Omar-Abdul-Aziz** [openai/mujoco-py#681]
I'm trying to run a mujoco_py file and I'm getting this error. I'm stucking with a lot of set path comments but I'm not able to do so. 
Can someone help me to set this path please?

Traceback (most recent call last):
  File "C:/Users/USER/Desktop/FYP/python/mujocotest.py", line 1, in <module>
    import mujoco_py
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\mujoco_py\__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\mujoco_py\builder.py", line 506, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python39\lib\site-packages\mujoco_py\builder.py", line 78, in load_cython_ext
    raise Exception("Please add mujoco library to your PATH:\n"
Exception: Please add mujoco library to your PATH:
set PATH=C:\Users\USER\.mujoco\mujoco200\bin;%PATH%

**Comment by nikhild05** [comment]
I'm facing the same issue right now. Did you find any solution to this?
