### ISSUE TITLE
import mujoco_py stalled

### ISSUE THREAD

**Issue by jgwak1** [openai/mujoco-py#697]
Ubuntu 18.04
python 3.8

"import "mujoco_py" gets stalled and as it appears that it got stuck in some process_lock. (as I CTRL-C) 
I would appreciate some help here.

>>> import mujoco_py

^CTraceback (most recent call last):
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/process_lock.py", line 78, in _try_acquire
    self.trylock()
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/process_lock.py", line 195, in trylock
    self._trylock(self.lockfile)
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/process_lock.py", line 431, in _trylock
    fcntl.lockf(lockfile, fcntl.LOCK_EX | fcntl.LOCK_NB)
BlockingIOError: [Errno 11] Resource temporarily unavailable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/_utils.py", line 103, in __call__
    return fn(*args, **kwargs)
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/process_lock.py", line 84, in _try_acquire
    raise _utils.RetryAgain()
fasteners._utils.RetryAgain

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jgwak1/.local/lib/python3.8/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/jgwak1/.local/lib/python3.8/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/jgwak1/.local/lib/python3.8/site-packages/mujoco_py/builder.py", line 94, in load_cython_ext
    with fasteners.InterProcessLock(lockpath):
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/process_lock.py", line 157, in __enter__
    gotten = self.acquire()
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/process_lock.py", line 140, in acquire
    gotten = r(self._try_acquire, blocking, watch)
  File "/home/jgwak1/.local/lib/python3.8/site-packages/fasteners/_utils.py", line 115, in __call__
    self.sleep_func(actual_delay)
KeyboardInterrupt

**Comment by chenxi-yang** [comment]
I met the same problem, did you solve this? Thanks!
