### ISSUE TITLE
import mujoco_py error!

### ISSUE THREAD

**Issue by mhmd97z** [openai/mujoco-py#715]
I followed the README instructions and also added mujoco200 to ~/.mujoco/, but I'm receiving the following error when it comes to importing mujoco_py

```
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /u4/mzangooei/anaconda3/envs/macpo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py -I/u4/mzangooei/.mujoco/mujoco200/include -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/numpy/core/include -I/u4/mzangooei/anaconda3/envs/macpo/include/python3.7m -c /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/cymj.c -o /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /u4/mzangooei/anaconda3/envs/macpo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py -I/u4/mzangooei/.mujoco/mujoco200/include -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/numpy/core/include -I/u4/mzangooei/anaconda3/envs/macpo/include/python3.7m -c /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/gl/osmesashim.c -o /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/gl/osmesashim.c:1:10: fatal error: GL/osmesa.h: No such file or directory
 #include <GL/osmesa.h>
          ^~~~~~~~~~~~~
compilation terminated.
Traceback (most recent call last):
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/unixccompiler.py", line 174, in _compile
    extra_postargs)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 917, in spawn
    spawn(cmd, dry_run=self.dry_run, **kwargs)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/spawn.py", line 69, in spawn
    "command %r failed with exit code %s" % (cmd, exitcode))
distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/builder.py", line 506, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/builder.py", line 273, in _build_impl
    so_file_path = super()._build_impl()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/setuptools/_distutils/unixccompiler.py", line 176, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
```

**Comment by zzu-zhangzhen** [comment]
i have same issue !

**Comment by ruze00** [comment]
```
sudo apt-get install libosmesa6-dev
sudo apt-get install patchelf
```

Honestly, with all the issues and missing docs I wonder if this has been put out by 3rd graders!

**Comment by mhmd97z** [comment]
Thanks, @ruze00 
Moving on, now I have another error to deal with!

```>>> import mujoco_py
running build_ext
building 'mujoco_py.cymj' extension
gcc -pthread -B /u4/mzangooei/anaconda3/envs/macpo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py -I/u4/mzangooei/.mujoco/mujoco200/include -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/numpy/core/include -I/u4/mzangooei/anaconda3/envs/macpo/include/python3.7m -c /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/cymj.c -o /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/cymj.o -fopenmp -w
gcc -pthread -B /u4/mzangooei/anaconda3/envs/macpo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py -I/u4/mzangooei/.mujoco/mujoco200/include -I/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/numpy/core/include -I/u4/mzangooei/anaconda3/envs/macpo/include/python3.7m -c /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/gl/osmesashim.c -o /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
creating /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/lib.linux-x86_64-3.7
creating /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/lib.linux-x86_64-3.7/mujoco_py
gcc -pthread -shared -B /u4/mzangooei/anaconda3/envs/macpo/compiler_compat -L/u4/mzangooei/anaconda3/envs/macpo/lib -Wl,-rpath=/u4/mzangooei/anaconda3/envs/macpo/lib -Wl,--no-as-needed -Wl,--sysroot=/ /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/cymj.o /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/temp.linux-x86_64-3.7/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/gl/osmesashim.o -L/u4/mzangooei/.mujoco/mujoco200/bin -Wl,-R/u4/mzangooei/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/generated/_pyxbld_2.0.2.8_37_linuxcpuextensionbuilder/lib.linux-x86_64-3.7/mujoco_py/cymj.cpython-37m-x86_64-linux-gnu.so -fopenmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/__init__.py", line 6, in <module>
    from mujoco_py.mjviewer import MjViewer, MjViewerBasic
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/mujoco_py/mjviewer.py", line 2, in <module>
    import glfw
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/glfw/__init__.py", line 65, in <module>
    ffi = FFI()
  File "/u4/mzangooei/anaconda3/envs/macpo/lib/python3.7/site-packages/cffi/api.py", line 48, in __init__
    import _cffi_backend as backend
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
```

**Comment by ruze00** [comment]
I haven't had that issue, but this discussion might help:

https://askubuntu.com/questions/1286772/libffi-so-7-cannot-open-shared-object-file-no-such-file-or-directory

**Comment by ruze00** [comment]
Also, I haven't tried this yet but if you're on Windows I hear a conda install is the way to go.
