### ISSUE TITLE
Found 0 GPUs for rendering. Using device 0.RuntimeError: Failed to initialize OpenGL

### ISSUE THREAD

**Issue by xuweiqiang486** [openai/mujoco-py#717]
**Describe the bug**
viewer = mujoco_py.MjRenderContextOffscreen(sim)

**Error Messages**
Found 0 GPUs for rendering. Using device 0.
Device id outside of range of available devices.
Traceback (most recent call last):
  File "/home/xwq/桌面/robustified/shiyan.py", line 86, in <module>
    viewer = mujoco_py.MjRenderContextOffscreen(sim)
  File "mjrendercontext.pyx", line 46, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 114, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "opengl_context.pyx", line 130, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04.4 LTS]
 - Python Version [3.7.13]
 - Mujoco Version [210]
 - mujoco-py version [2.1.2.14]

**Environment**
 - output of: `echo $LD_LIBRARY_PATH` LD_LIBRARY_PATH:/home/xwq/.mujoco/mujoco210/bin:/usr/lib/nvidia:/usr/lib/nvidia-000
 - output of: `echo $HOME` /home/xwq
 - output of: `echo $USER` xwq
 - output of: `echo $LD_PRELOAD` /usr/lib/x86_64-linux-gnu/libGLEW.so

**Comment by yhogewind** [comment]
For offscreen rendering you should not preload libGLEW. So execute the following in your terminal:
`unset LD_PRELOAD`

Unless you must use mujoco-py, you are probably best off moving over to [deepmind/mujoco](https://github.com/deepmind/mujoco)
