### ISSUE TITLE
Could not get EGL display

### ISSUE THREAD

**Issue by YouJiacheng** [openai/mujoco-py#731]
**Describe the bug**
Failed to initialize OpenGL with message "Could not get EGL display"

**To Reproduce**
```python
import mujoco_py
import os
xml_path = os.path.join(mujoco_py.utils.discover_mujoco(), 'model', 'humanoid.xml')
model = mujoco_py.load_model_from_path(xml_path)
sim = mujoco_py.MjSim(model)
sim.render(480, 480)
```

**Expected behavior**
Successfully rendering offscreen

**Error Messages**
```
Found 6 GPUs for rendering. Using device 0.
Could not get EGL display
Traceback (most recent call last):
  ... omitted
  File "mjsim.pyx", line 156, in mujoco_py.cymj.MjSim.render
  File "mjsim.pyx", line 158, in mujoco_py.cymj.MjSim.render
  File "mjrendercontext.pyx", line 46, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 114, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "opengl_context.pyx", line 130, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL
```

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009
 - Python Version 3.10.4
 - Mujoco Version 2.1
 - mujoco-py version 2.1.2.14

**Environment**
 - output of: `ldd cymj_2.1.2.14_310_linuxgpuextensionbuilder_310.so`
```
        linux-vdso.so.1 =>  (0x00007fff2f712000)
        libglewegl.so => /home/youjiacheng/.mujoco/mujoco210/bin/libglewegl.so (0x00002ae3dc312000)
        libmujoco210.so => /home/youjiacheng/.mujoco/mujoco210/bin/libmujoco210.so (0x00002ae3dc5b6000)
        libEGL.so.1 => /lib64/libEGL.so.1 (0x00002ae3dc97c000)
        libOpenGL.so.0 => /lib64/libOpenGL.so.0 (0x00002ae3dcb90000)
        libgomp.so.1 => /lib64/libgomp.so.1 (0x00002ae3dcdbe000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002ae3dcfe4000)
        libc.so.6 => /lib64/libc.so.6 (0x00002ae3dd200000)
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002ae3dd5ce000)
        libm.so.6 => /lib64/libm.so.6 (0x00002ae3dd8d6000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002ae3ddbd8000)
        libGLdispatch.so.0 => /lib64/libGLdispatch.so.0 (0x00002ae3dddee000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00002ae3de0a4000)
        /lib64/ld-linux-x86-64.so.2 (0x00002ae3dc0ee000)
```

**Additional context**
- I follow https://github.com/openai/mujoco-py/issues/627 to install dependencies.
- LinuxGPUExtensionBuilder.build() seems successful, since `cymj_2.1.2.14_310_linuxgpuextensionbuilder_310.so` is generated.
- nvidia-smi shows there are 4 RTX3080s, but `eglshim` reports there are 6 GPUs.
- I try specifying device_id in `sim.render(64, 64, camera_name="cam0", device_id=device_id)`, but `device_id` from 0 to 5 give the same error.

**Comment by YouJiacheng** [comment]
After I reinstall Nvidia Driver with OpenGL Driver the problem is solved.
And actually only `conda install -c conda-forge glew` is needed, `mesalib`(for OSMesa) and `glfw`(for onscreen GPU rendering) have nothing to do with headless GPU rendering. Also, no `CPATH` need to be set.
