### ISSUE TITLE
Mujoco Installation issue on Mac

### ISSUE THREAD

**Issue by soumyajit-dey** [openai/mujoco-py#760]
**Describe the bug**
While doing
python3
>>import mujoco_py 

**Error Messages**
 running build_ext
building 'mujoco_py.cymj' extension
/usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/usr/local/opt/llvm/include -DONMAC -I/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py -I/Users/soumya/PycharmProjects/mujoco/mujoco210/include -I/Users/soumya/Library/Python/3.9/lib/python/site-packages/numpy/core/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -c /Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/cymj.c -o /Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_39_macextensionbuilder/temp.macosx-10.9-universal2-3.9/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/cymj.o -fopenmp -w
/usr/local/opt/llvm/bin/clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/usr/local/opt/llvm/include -DONMAC -I/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py -I/Users/soumya/PycharmProjects/mujoco/mujoco210/include -I/Users/soumya/Library/Python/3.9/lib/python/site-packages/numpy/core/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -c /Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/gl/dummyshim.c -o /Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_39_macextensionbuilder/temp.macosx-10.9-universal2-3.9/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/gl/dummyshim.o -fopenmp -w
/usr/local/opt/llvm/bin/clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -Wl,-headerpad,0x1000 -L/usr/local/opt/llvm/lib -I/usr/local/opt/llvm/include /Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_39_macextensionbuilder/temp.macosx-10.9-universal2-3.9/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/cymj.o /Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_39_macextensionbuilder/temp.macosx-10.9-universal2-3.9/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/gl/dummyshim.o -L/Users/soumya/PycharmProjects/mujoco/mujoco210/bin -L/Users/soumya/PycharmProjects/mujoco/mujoco210/bin -lmujoco210 -lglfw.3 -o /Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/generated/_pyxbld_2.1.2.14_39_macextensionbuilder/lib.macosx-10.9-universal2-3.9/mujoco_py/cymj.cpython-39-darwin.so -fopenmp
ld: warning: ignoring file /Users/soumya/PycharmProjects/mujoco/mujoco210/bin/libglfw.3.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64ld: warning: ld: warning: 
ignoring file /usr/local/opt/llvm/lib/libomp.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ignoring file /Users/soumya/PycharmProjects/mujoco/mujoco210/bin/libmujoco210.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: in '/usr/local/opt/llvm/lib/libunwind.dylib', building for macOS-arm64 but attempting to link with file built for macOS-x86_64
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 205, in link
    self.spawn(linker + ld_args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 910, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/spawn.py", line 91, in spawn
    raise DistutilsExecError(
distutils.errors.DistutilsExecError: command '/usr/local/opt/llvm/bin/clang' failed with exit code 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/builder.py", line 110, in load_cython_ext
    cext_so_path = builder.build()
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/builder.py", line 226, in build
    built_so_file_path = self._build_impl()
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/builder.py", line 343, in _build_impl
    so_file_path = super()._build_impl()
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/builder.py", line 249, in _build_impl
    dist.run_commands()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/mujoco_py/builder.py", line 149, in build_extensions
    build_ext.build_extensions(self)
  File "/Users/soumya/Library/Python/3.9/lib/python/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/command/build_ext.py", line 551, in build_extension
    self.compiler.link_shared_object(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/ccompiler.py", line 713, in link_shared_object
    self.link(CCompiler.SHARED_OBJECT, objects,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/distutils/unixccompiler.py", line 207, in link
    raise LinkError(msg)
distutils.errors.LinkError: command '/usr/local/opt/llvm/bin/clang' failed with exit code 1
>>> 

 

**Desktop (please complete the following information):**
 -  macOS 13  on 2 GHz Quad-Core Intel Core i5
 - Mujoco Version : mujoco==2.3.1.post1
 - mujoco-py version  : mujoco-py<2.2,>=2.1

**Environment**
 - output of: `echo $LD_LIBRARY_PATH`
  /Users/soumya/PycharmProjects/mujoco/mujoco210/bin
 - output of: `echo $HOME`
 - /Users/soumya
 - output of: `echo $USER`
soumya
**Additional context**

**Comment by chulhongsung** [comment]
I have same issue.
