### ISSUE TITLE
Fail to import mujoco_py

### ISSUE THREAD

**Issue by hsyfpv** [openai/mujoco-py#789]
After following the instruction, I try to import  mujoco_py on my macbook pro m3pro, I got this error.

(drone_pybullet) hsy@hsydeMacBook-Pro ~ % python -c 'import mujoco_py'
Import error. Trying to rebuild mujoco_py.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/__init__.py", line 2, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 504, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 111, in load_cython_ext
    mod = load_dynamic_ext('cymj', cext_so_path)
  File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 130, in load_dynamic_ext
    return loader.load_module()
ImportError: dlopen(/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/generated/cymj_2.1.2.14_310_macextensionbuilder_310.so, 0x0002): symbol not found in flat namespace '__PyGen_Send'

**Comment by hsyfpv** [comment]
I solved this problem by downgrading my Python version to 3.9!

**Comment by hsyfpv** [comment]
> After following the instruction, I try to import mujoco_py on my macbook pro m3pro, I got this error.
> 
> (drone_pybullet) hsy@hsydeMacBook-Pro ~ % python -c 'import mujoco_py' Import error. Trying to rebuild mujoco_py. Traceback (most recent call last): File "", line 1, in File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/**init**.py", line 2, in from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 504, in cymj = load_cython_ext(mujoco_path) File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 111, in load_cython_ext mod = load_dynamic_ext('cymj', cext_so_path) File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 130, in load_dynamic_ext return loader.load_module() ImportError: dlopen(/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/generated/cymj_2.1.2.14_310_macextensionbuilder_310.so, 0x0002): symbol not found in flat namespace '__PyGen_Send'
> 
> ### Tasks
> 
> Beta
> [Give feedback](https://github.com/community/community/discussions/39106)
> 
> No tasks being tracked yet.
> 1. [ ] 
>                  
>                
>    
>                
>                  
>                    
>    
>                  
>                    
>                
>              
>              
>                
>      
>          
>        
>    
>    Options
>    
>    
>    
>      
>        
>                    
>      
>          * Convert to issue
>          * Toggle completion
>          * Rename
>          * Remove
> 2.

I solved this problem by downgrading my Python version to 3.9!

**Comment by hsyfpv** [comment]
> After following the instruction, I try to import mujoco_py on my macbook pro m3pro, I got this error.
> 
> (drone_pybullet) hsy@hsydeMacBook-Pro ~ % python -c 'import mujoco_py' Import error. Trying to rebuild mujoco_py. Traceback (most recent call last): File "", line 1, in File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/**init**.py", line 2, in from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 504, in cymj = load_cython_ext(mujoco_path) File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 111, in load_cython_ext mod = load_dynamic_ext('cymj', cext_so_path) File "/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/builder.py", line 130, in load_dynamic_ext return loader.load_module() ImportError: dlopen(/Users/hsy/anaconda3/envs/drone_pybullet/lib/python3.10/site-packages/mujoco_py/generated/cymj_2.1.2.14_310_macextensionbuilder_310.so, 0x0002): symbol not found in flat namespace '__PyGen_Send'


I solved this problem by downgrading my Python version to 3.9!
