### ISSUE TITLE
GLFW initialization error with GLX version 1.3

### ISSUE THREAD

**Issue by jaesik817** [openai/mujoco-py#86]
Hi, 

This is Jaesik Yoon.

I tried to use this on my reseach,

however I got an error when I ran marker_demo.py as followed.
`
GLFW error (code %d): %s 65542 b'GLX: GLX version 1.3 is required'
GLFW error (code %d): %s 65542 b'GLX: GLX version 1.3 is required'
Traceback (most recent call last):
  File "examples/markers_demo.py", line 28, in <module>
    viewer = MjViewer(sim)
  File "/usr/local/lib/python3.5/dist-packages/mujoco_py-1.50.1.14-py3.5.egg/mujoco_py/mjviewer.py", line 132, in __init__
    super().__init__(sim)
  File "/usr/local/lib/python3.5/dist-packages/mujoco_py-1.50.1.14-py3.5.egg/mujoco_py/mjviewer.py", line 26, in __init__
    super().__init__(sim)
  File "mjrendercontext.pyx", line 252, in mujoco_py.cymj.MjRenderContextWindow.__init__
  File "mjrendercontext.pyx", line 43, in mujoco_py.cymj.MjRenderContext.__init__
  File "mjrendercontext.pyx", line 92, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "opengl_context.pyx", line 44, in mujoco_py.cymj.GlfwContext.__init__
  File "opengl_context.pyx", line 64, in mujoco_py.cymj.GlfwContext._init_glfw
mujoco_py.cymj.GlfwError: Failed to initialize GLFW
`
I did try to update GLX, however I did not find the solution.

My server info.

Ubuntu 16.04.2
Geforce 1060

Thanks.

Jaesik Yoon.

**Comment by jaesik817** [comment]
I did try that with putty and Xming. In that time, I only got GLX version: 1.2. However, I changed terminal from that to MobaXterm, and got GLX version: 1.4.

I closed this one.
